class_name GunDefs
extends RefCounted
## NOVA arsenal data: ~42 original gun designs across all CODM weapon types.
## Pure data + stat helpers. Models built by GunModels, sounds by GunAudio.
##
## Model spec fields (interpreted by GunModels):
##   style  - silhouette family within the class
##   barrel - barrel length in meters
##   mag    - "curved" | "straight" | "drum" | "box" | "tube" | "stick" | "internal" | "none"
##   stock  - "fixed" | "folding" | "skeleton" | "bullpup" | "wire" | "none"
##   sight  - "iron" | "reddot" | "holo" | "scope" | "scopelong" | "none"
##   muzzle - "flash" | "suppressor" | "comp" | "brake" | "none"
##   body   - color scheme: "black" | "gunmetal" | "tan" | "od" | "grey" | "white" | "sand"
##   accent - "wood" | "tan" | "none"
##   extras - ["foregrip","bipod","laser","drum","heatshield","bayonet","carry"]

const AMMO_START := {
	"light": 240, "medium": 150, "heavy": 40,
	"shell": 24, "rocket": 4, "grenade": 6, "none": 0,
}

# Attachment definitions: slot -> id -> {name, mods}.
# mods keys: dmg, rpm, rec, ads, magadd, spread, range, silent, vel
const ATTACHMENTS := {
	"muzzle": {
		"suppressor": {"name": "VX Suppressor", "dmg": 0.92, "rec": 0.82, "range": 0.9, "silent": true, "ads": 1.06},
		"compensator": {"name": "Tri-Port Comp", "rec": 0.78, "ads": 1.04},
		"flashhider": {"name": "Birdcage FH", "rec": 0.92, "spread": 0.94},
		"brake": {"name": "Tanker Brake", "rec": 0.72, "spread": 1.08, "ads": 1.05},
	},
	"optic": {
		"reddot": {"name": "RD-1 Dot", "ads": 0.94, "spread": 0.92},
		"holo": {"name": "HX Holo", "ads": 0.96, "spread": 0.9},
		"scope4": {"name": "4x Ranger", "ads": 1.18, "range": 1.15, "zoom": 4.0},
		"scope8": {"name": "8x Longeye", "ads": 1.3, "range": 1.25, "zoom": 8.0},
	},
	"magazine": {
		"extended": {"name": "Ext. Mag", "magadd": 12, "ads": 1.06, "reload": 1.1},
		"fast": {"name": "Speed Mag", "reload": 0.8, "magadd": -4},
		"drum": {"name": "Drum 60", "magadd": 30, "ads": 1.12, "move": 0.97, "reload": 1.25},
	},
	"underbarrel": {
		"foregrip": {"name": "Vert Grip", "rec": 0.85, "spread": 0.94},
		"bipod": {"name": "Tact. Bipod", "rec": 0.7, "ads": 1.1, "move": 0.98},
		"laser": {"name": "Tac Laser", "spread": 0.8, "ads": 0.95},
	},
}

# Attachment loot pickups that can appear in the world.
const ATTACH_LOOT := ["suppressor", "compensator", "reddot", "holo", "extended", "foregrip", "laser", "scope4"]

const SLOT_OF := {
	"ar": "primary", "smg": "primary", "lmg": "primary", "sniper": "primary",
	"marksman": "primary", "shotgun": "primary",
	"pistol": "secondary", "launcher": "secondary",
	"melee": "melee",
}

const CLASS_NAMES := {
	"ar": "Assault Rifle", "smg": "SMG", "lmg": "LMG", "sniper": "Sniper",
	"marksman": "Marksman", "shotgun": "Shotgun",
	"pistol": "Pistol", "launcher": "Launcher", "melee": "Melee",
}


static func all() -> Array:
	return _ROSTER


static func by_id(gid: String) -> Dictionary:
	for g in _ROSTER:
		if g["id"] == gid:
			return g
	return {}


static func slot_of(cls: String) -> String:
	return SLOT_OF.get(cls, "primary")


static func class_name_of(cls: String) -> String:
	return CLASS_NAMES.get(cls, cls)


static func full_name(g: Dictionary) -> String:
	return str(g["name"]) + " \"" + str(g["alias"]) + "\""


## Damage with linear falloff between range_near and range_far, min 35% past far.
static func damage_at_range(g: Dictionary, dist: float) -> float:
	var dmg: float = g["damage"]
	var rn: float = g["range_near"]
	var rf: float = g["range_far"]
	if dist <= rn:
		return dmg
	if dist >= rf:
		return dmg * 0.35
	var t: float = (dist - rn) / maxf(rf - rn, 0.01)
	return dmg * lerpf(1.0, 0.35, t)


## CODM-style headshot multipliers by class.
const HEADSHOT_MULT := {
	"sniper": 2.0, "marksman": 1.8, "ar": 1.6, "smg": 1.5, "lmg": 1.5,
	"shotgun": 1.5, "pistol": 1.5, "launcher": 1.0, "melee": 1.0,
}


static func headshot_mult(cls: String) -> float:
	return float(HEADSHOT_MULT.get(cls, 1.5))


## Shots-to-kill vs 100 HP (body) and vs 150 armor + 100 HP (armored),
## at close range, all shots landing. Shotguns assume all pellets hit.
## Returns {"body": int, "head": int, "armored_body": int, "armored_head": int}.
static func shots_to_kill(g: Dictionary) -> Dictionary:
	var cls := str(g["cls"])
	var pellets := int(g.get("pellets", 1))
	var dmg: float = float(g["damage"])
	if cls == "shotgun":
		dmg *= float(maxi(pellets, 1))
	if dmg <= 0.0:
		return {"body": 99, "head": 99, "armored_body": 99, "armored_head": 99}
	var hm := headshot_mult(cls)
	var body := int(ceil(100.0 / dmg))
	var head := int(ceil(100.0 / (dmg * hm)))
	var abody := int(ceil(250.0 / dmg))
	var ahead := int(ceil(250.0 / (dmg * hm)))
	if cls == "melee":
		# Melee is per-swing; keep raw numbers.
		pass
	return {"body": body, "head": head, "armored_body": abody, "armored_head": ahead}


## Short STK string for the HUD weapon panel, e.g. "4 SHOTS · 3 HEAD".
static func stk_label(g: Dictionary) -> String:
	var s := shots_to_kill(g)
	var cls := str(g["cls"])
	if cls == "launcher":
		return "1 BLAST KILL"
	if cls == "melee":
		return "%d SWINGS" % int(s["body"])
	return "%d SHOTS · %d HEAD" % [int(s["body"]), int(s["head"])]



## Effective stats after attachments. Returns a fresh Dictionary (numbers only).
static func effective(g: Dictionary, attach: Array) -> Dictionary:
	var e := {
		"damage": float(g["damage"]), "rpm": float(g["rpm"]),
		"range_near": float(g["range_near"]), "range_far": float(g["range_far"]),
		"mag": int(g["mag"]), "ads": float(g["ads"]), "move": float(g["move"]),
		"spread": float(g["hip_spread"]), "recv": float(g["recoil_v"]),
		"rech": float(g["recoil_h"]), "reload": float(g["reload"]),
		"silent": bool(g.get("silent", false)), "zoom": float(g.get("zoom", 0.0)),
	}
	for aid in attach:
		var m := find_attach(aid)
		if m.is_empty():
			continue
		if m.has("dmg"): e["damage"] *= float(m["dmg"])
		if m.has("rpm"): e["rpm"] *= float(m["rpm"])
		if m.has("rec"):
			e["recv"] *= float(m["rec"])
			e["rech"] *= float(m["rec"])
		if m.has("ads"): e["ads"] *= float(m["ads"])
		if m.has("magadd"): e["mag"] = maxi(1, int(e["mag"]) + int(m["magadd"]))
		if m.has("spread"): e["spread"] *= float(m["spread"])
		if m.has("range"):
			e["range_near"] *= float(m["range"])
			e["range_far"] *= float(m["range"])
		if m.has("move"): e["move"] *= float(m["move"])
		if m.has("reload"): e["reload"] *= float(m["reload"])
		if m.has("zoom"): e["zoom"] = float(m["zoom"])
		if bool(m.get("silent", false)): e["silent"] = true
	return e


static func find_attach(aid: String) -> Dictionary:
	for slot in ATTACHMENTS.keys():
		var d: Dictionary = ATTACHMENTS[slot]
		if d.has(aid):
			var m: Dictionary = (d[aid] as Dictionary).duplicate()
			m["slot"] = slot
			m["id"] = aid
			return m
	return {}


static func attach_slot(aid: String) -> String:
	var a := find_attach(aid)
	return str(a.get("slot", ""))


## Tier-weighted random gun id. Higher tier -> deadlier classes.
static func roll_gun(tier: int, rng: RandomNumberGenerator) -> String:
	var pool: Array = []
	for g in _ROSTER:
		var cls: String = g["cls"]
		var w := 1.0
		match cls:
			"pistol", "melee":
				w = 3.0 if tier <= 1 else 0.4
			"shotgun", "smg":
				w = 2.5 if tier <= 2 else 1.0
			"ar":
				w = 1.5 if tier <= 1 else 2.5
			"marksman":
				w = 0.4 if tier <= 1 else 2.0
			"lmg", "sniper":
				w = 0.3 if tier <= 2 else 2.2
			"launcher":
				w = 0.15 if tier <= 2 else 1.2
		# Launchers/melee never from plain ground tier 0.
		if tier == 0 and (cls == "launcher"):
			w = 0.0
		# RP-7 Thunderhead: high-tier menace — boosted at epic/legendary.
		if str(g["id"]) == "rp7" and tier >= 4:
			w = 2.4
		if w > 0.0:
			pool.append([g["id"], w])
	var total := 0.0
	for p in pool:
		total += float(p[1])
	var r: float = rng.randf() * total
	for p in pool:
		r -= float(p[1])
		if r <= 0.0:
			return str(p[0])
	return "m5"


## Default attachments pre-equipped by loot tier (grey->orange).
static func tier_attachments(tier: int, rng: RandomNumberGenerator) -> Array:
	var out: Array = []
	if tier >= 3:
		var cands := ["reddot", "foregrip", "extended", "compensator"]
		out.append(cands[rng.randi() % cands.size()])
	if tier >= 4:
		var c2 := ["holo", "suppressor", "laser", "extended"]
		var pick: String = c2[rng.randi() % c2.size()]
		if not out.has(pick):
			out.append(pick)
	if tier >= 5:
		if not out.has("suppressor"):
			out.append("suppressor")
	return out


# ---------------------------------------------------------------- roster ---
# damage, rpm, range_near, range_far, mag, reserve0, ads, move, hip_spread,
# recoil_v, recoil_h, reload, ammo, mode, pen, zoom, silent
# mode: auto | semi | burst | pump | bolt | melee | rocket | grenade
static var _ROSTER: Array = [
	# ------------------------- ASSAULT RIFLES (medium) -------------------------
	{"id": "kv47", "name": "KV-47", "alias": "Warlord", "cls": "ar",
		"damage": 33, "rpm": 545, "range_near": 32.0, "range_far": 65.0,
		"mag": 30, "reserve0": 120, "ads": 0.30, "move": 0.93, "hip_spread": 0.014,
		"recoil_v": 0.017, "recoil_h": 0.011, "reload": 2.2, "ammo": "medium",
		"mode": "auto", "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 0.94,
		"role": "Long-stroke piston rifle. Hits hard, kicks hard.",
		"model": {"style": "piston", "barrel": 0.42, "mag": "curved", "stock": "fixed",
			"sight": "iron", "muzzle": "flash", "body": "gunmetal", "accent": "wood", "extras": ["bayonet"]}},
	{"id": "m5", "name": "M5", "alias": "Sentinel", "cls": "ar",
		"damage": 30, "rpm": 625, "range_near": 30.0, "range_far": 60.0,
		"mag": 30, "reserve0": 120, "ads": 0.26, "move": 0.95, "hip_spread": 0.013,
		"recoil_v": 0.015, "recoil_h": 0.010, "reload": 1.9, "ammo": "medium",
		"mode": "auto", "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 1.0,
		"role": "Modular carbine. The balanced all-rounder.",
		"model": {"style": "modular", "barrel": 0.38, "mag": "straight", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "black", "accent": "none", "extras": ["foregrip"]}},
	{"id": "br9", "name": "BR-9", "alias": "Bastion", "cls": "ar",
		"damage": 42, "rpm": 460, "range_near": 38.0, "range_far": 75.0,
		"mag": 24, "reserve0": 96, "ads": 0.32, "move": 0.90, "hip_spread": 0.016,
		"recoil_v": 0.022, "recoil_h": 0.013, "reload": 2.3, "ammo": "medium",
		"mode": "auto", "pen": 1.2, "zoom": 0.0, "silent": false, "pitch": 0.88,
		"role": "Heavy battle rifle. Slow, punishing, long reach.",
		"model": {"style": "battle", "barrel": 0.48, "mag": "straight", "stock": "fixed",
			"sight": "iron", "muzzle": "brake", "body": "grey", "accent": "none", "extras": ["carry"]}},
	{"id": "vk3", "name": "VK-3", "alias": "Triplet", "cls": "ar",
		"damage": 31, "rpm": 700, "range_near": 30.0, "range_far": 62.0,
		"mag": 30, "reserve0": 120, "ads": 0.27, "move": 0.94, "hip_spread": 0.013,
		"recoil_v": 0.016, "recoil_h": 0.012, "reload": 2.0, "ammo": "medium",
		"mode": "burst", "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 1.04,
		"role": "3-round burst rifle. Laser at mid range.",
		"model": {"style": "burst", "barrel": 0.44, "mag": "curved", "stock": "skeleton",
			"sight": "reddot", "muzzle": "flash", "body": "od", "accent": "none", "extras": []}},
	{"id": "rf15", "name": "RF-15", "alias": "Hornet", "cls": "ar",
		"damage": 26, "rpm": 800, "range_near": 24.0, "range_far": 50.0,
		"mag": 32, "reserve0": 128, "ads": 0.24, "move": 0.96, "hip_spread": 0.015,
		"recoil_v": 0.013, "recoil_h": 0.012, "reload": 2.0, "ammo": "medium",
		"mode": "auto", "pen": 0.9, "zoom": 0.0, "silent": false, "pitch": 1.1,
		"role": "High-RPM shredder. Melts up close.",
		"model": {"style": "shredder", "barrel": 0.34, "mag": "straight", "stock": "wire",
			"sight": "iron", "muzzle": "comp", "body": "black", "accent": "none", "extras": ["heatshield"]}},
	{"id": "cr56", "name": "CR-56", "alias": "Nomad", "cls": "ar",
		"damage": 29, "rpm": 680, "range_near": 22.0, "range_far": 48.0,
		"mag": 30, "reserve0": 120, "ads": 0.23, "move": 0.97, "hip_spread": 0.014,
		"recoil_v": 0.014, "recoil_h": 0.011, "reload": 1.8, "ammo": "medium",
		"mode": "auto", "pen": 0.9, "zoom": 0.0, "silent": false, "pitch": 1.06,
		"role": "Compact PDW-rifle. Fast handling, close quarters.",
		"model": {"style": "compact", "barrel": 0.28, "mag": "straight", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "tan", "accent": "none", "extras": []}},
	{"id": "ag2", "name": "AG-2", "alias": "Anvil", "cls": "ar",
		"damage": 32, "rpm": 600, "range_near": 30.0, "range_far": 62.0,
		"mag": 30, "reserve0": 120, "ads": 0.27, "move": 0.94, "hip_spread": 0.013,
		"recoil_v": 0.016, "recoil_h": 0.010, "reload": 2.2, "ammo": "medium",
		"mode": "auto", "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 0.97,
		"role": "Bullpup rifle. Full barrel, compact body.",
		"model": {"style": "bullpup", "barrel": 0.40, "mag": "curved", "stock": "bullpup",
			"sight": "holo", "muzzle": "flash", "body": "od", "accent": "none", "extras": []}},
	{"id": "st44", "name": "ST-44", "alias": "Stormfront", "cls": "ar",
		"damage": 36, "rpm": 520, "range_near": 34.0, "range_far": 68.0,
		"mag": 30, "reserve0": 120, "ads": 0.30, "move": 0.92, "hip_spread": 0.014,
		"recoil_v": 0.018, "recoil_h": 0.011, "reload": 2.3, "ammo": "medium",
		"mode": "auto", "pen": 1.1, "zoom": 0.0, "silent": false, "pitch": 0.9,
		"role": "Wooden-furniture classic. Old soul, heavy punch.",
		"model": {"style": "classic", "barrel": 0.46, "mag": "curved", "stock": "fixed",
			"sight": "iron", "muzzle": "none", "body": "gunmetal", "accent": "wood", "extras": ["bayonet"]}},
	{"id": "xr7", "name": "XR-7", "alias": "Vortex", "cls": "ar",
		"damage": 28, "rpm": 720, "range_near": 28.0, "range_far": 58.0,
		"mag": 36, "reserve0": 144, "ads": 0.22, "move": 0.97, "hip_spread": 0.012,
		"recoil_v": 0.013, "recoil_h": 0.010, "reload": 1.9, "ammo": "medium",
		"mode": "auto", "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 1.08,
		"role": "Advanced polymer rifle. Fastest ADS in class.",
		"model": {"style": "advanced", "barrel": 0.36, "mag": "straight", "stock": "skeleton",
			"sight": "reddot", "muzzle": "comp", "body": "white", "accent": "none", "extras": ["laser"]}},
	# ---------------------------------- SMGs (light) ----------------------------------
	{"id": "mp9", "name": "MP-9", "alias": "Wasp", "cls": "smg",
		"damage": 24, "rpm": 800, "range_near": 16.0, "range_far": 34.0,
		"mag": 32, "reserve0": 160, "ads": 0.20, "move": 1.0, "hip_spread": 0.016,
		"recoil_v": 0.012, "recoil_h": 0.012, "reload": 1.8, "ammo": "light",
		"mode": "auto", "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.12,
		"role": "Classic straight-mag SMG. Reliable bullet hose.",
		"model": {"style": "classic", "barrel": 0.22, "mag": "straight", "stock": "wire",
			"sight": "iron", "muzzle": "flash", "body": "black", "accent": "none", "extras": []}},
	{"id": "dg12", "name": "DG-12", "alias": "Drumline", "cls": "smg",
		"damage": 22, "rpm": 750, "range_near": 15.0, "range_far": 32.0,
		"mag": 64, "reserve0": 128, "ads": 0.24, "move": 0.98, "hip_spread": 0.017,
		"recoil_v": 0.013, "recoil_h": 0.013, "reload": 2.6, "ammo": "light",
		"mode": "auto", "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.05,
		"role": "Drum-mag SMG. 64 rounds of suppression.",
		"model": {"style": "drum", "barrel": 0.24, "mag": "drum", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "gunmetal", "accent": "none", "extras": []}},
	{"id": "sd6", "name": "SD-6", "alias": "Ghost", "cls": "smg",
		"damage": 23, "rpm": 700, "range_near": 18.0, "range_far": 38.0,
		"mag": 32, "reserve0": 160, "ads": 0.21, "move": 1.0, "hip_spread": 0.015,
		"recoil_v": 0.011, "recoil_h": 0.010, "reload": 1.9, "ammo": "light",
		"mode": "auto", "pen": 0.7, "zoom": 0.0, "silent": true, "pitch": 0.95,
		"role": "Integrally suppressed SMG. Silent killer.",
		"model": {"style": "suppressed", "barrel": 0.26, "mag": "straight", "stock": "folding",
			"sight": "iron", "muzzle": "suppressor", "body": "black", "accent": "none", "extras": []}},
	{"id": "p45", "name": "P45", "alias": "Bruiser", "cls": "smg",
		"damage": 34, "rpm": 550, "range_near": 15.0, "range_far": 32.0,
		"mag": 25, "reserve0": 125, "ads": 0.22, "move": 0.99, "hip_spread": 0.016,
		"recoil_v": 0.016, "recoil_h": 0.012, "reload": 2.0, "ammo": "light",
		"mode": "auto", "pen": 0.8, "zoom": 0.0, "silent": false, "pitch": 0.85,
		"role": "Heavy .45 SMG. Slow thump, big holes.",
		"model": {"style": "heavy", "barrel": 0.24, "mag": "straight", "stock": "fixed",
			"sight": "iron", "muzzle": "comp", "body": "od", "accent": "none", "extras": ["foregrip"]}},
	{"id": "vsk9", "name": "VSK-9", "alias": "Viper", "cls": "smg",
		"damage": 22, "rpm": 900, "range_near": 14.0, "range_far": 30.0,
		"mag": 30, "reserve0": 150, "ads": 0.18, "move": 1.02, "hip_spread": 0.017,
		"recoil_v": 0.011, "recoil_h": 0.013, "reload": 1.7, "ammo": "light",
		"mode": "auto", "pen": 0.6, "zoom": 0.0, "silent": false, "pitch": 1.2,
		"role": "Machine-pistol SMG. Fastest trigger in the game.",
		"model": {"style": "machine", "barrel": 0.16, "mag": "stick", "stock": "wire",
			"sight": "none", "muzzle": "flash", "body": "grey", "accent": "none", "extras": []}},
	{"id": "k10", "name": "K-10", "alias": "Cyclone", "cls": "smg",
		"damage": 25, "rpm": 850, "range_near": 15.0, "range_far": 32.0,
		"mag": 34, "reserve0": 170, "ads": 0.20, "move": 1.0, "hip_spread": 0.016,
		"recoil_v": 0.012, "recoil_h": 0.012, "reload": 1.8, "ammo": "light",
		"mode": "auto", "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.15,
		"role": "High-RPM SMG. Shreds at point blank.",
		"model": {"style": "rapid", "barrel": 0.20, "mag": "straight", "stock": "folding",
			"sight": "reddot", "muzzle": "flash", "body": "tan", "accent": "none", "extras": []}},
	{"id": "sg9", "name": "SG-9", "alias": "Stinger", "cls": "smg",
		"damage": 27, "rpm": 650, "range_near": 17.0, "range_far": 36.0,
		"mag": 28, "reserve0": 140, "ads": 0.21, "move": 0.99, "hip_spread": 0.015,
		"recoil_v": 0.013, "recoil_h": 0.011, "reload": 1.9, "ammo": "light",
		"mode": "auto", "pen": 0.75, "zoom": 0.0, "silent": false, "pitch": 1.02,
		"role": "Foregrip SMG. Controllable mid-range spray.",
		"model": {"style": "tactical", "barrel": 0.26, "mag": "curved", "stock": "skeleton",
			"sight": "holo", "muzzle": "flash", "body": "black", "accent": "tan", "extras": ["foregrip"]}},
	# ---------------------------------- LMGs (heavy) ----------------------------------
	{"id": "mg60", "name": "MG-60", "alias": "Thunder", "cls": "lmg",
		"damage": 32, "rpm": 550, "range_near": 34.0, "range_far": 70.0,
		"mag": 100, "reserve0": 100, "ads": 0.42, "move": 0.85, "hip_spread": 0.018,
		"recoil_v": 0.016, "recoil_h": 0.012, "reload": 4.2, "ammo": "heavy",
		"mode": "auto", "pen": 1.3, "zoom": 0.0, "silent": false, "pitch": 0.8,
		"role": "Belt-fed beast. Hold the lane forever.",
		"model": {"style": "belt", "barrel": 0.52, "mag": "box", "stock": "fixed",
			"sight": "iron", "muzzle": "brake", "body": "gunmetal", "accent": "none", "extras": ["bipod", "carry"]}},
	{"id": "bx200", "name": "BX-200", "alias": "Bulwark", "cls": "lmg",
		"damage": 30, "rpm": 600, "range_near": 32.0, "range_far": 66.0,
		"mag": 80, "reserve0": 80, "ads": 0.38, "move": 0.87, "hip_spread": 0.017,
		"recoil_v": 0.015, "recoil_h": 0.011, "reload": 3.8, "ammo": "heavy",
		"mode": "auto", "pen": 1.2, "zoom": 0.0, "silent": false, "pitch": 0.86,
		"role": "Box-mag support gun. Mobile suppression.",
		"model": {"style": "box", "barrel": 0.48, "mag": "box", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "od", "accent": "none", "extras": ["foregrip"]}},
	{"id": "lm7", "name": "LM-7", "alias": "Sawtooth", "cls": "lmg",
		"damage": 28, "rpm": 700, "range_near": 30.0, "range_far": 62.0,
		"mag": 60, "reserve0": 120, "ads": 0.34, "move": 0.90, "hip_spread": 0.016,
		"recoil_v": 0.014, "recoil_h": 0.011, "reload": 3.2, "ammo": "heavy",
		"mode": "auto", "pen": 1.1, "zoom": 0.0, "silent": false, "pitch": 0.92,
		"role": "Light LMG. AR handling, LMG mag.",
		"model": {"style": "light", "barrel": 0.44, "mag": "drum", "stock": "skeleton",
			"sight": "reddot", "muzzle": "comp", "body": "black", "accent": "none", "extras": []}},
	{"id": "pk8", "name": "PK-8", "alias": "Goliath", "cls": "lmg",
		"damage": 38, "rpm": 480, "range_near": 36.0, "range_far": 74.0,
		"mag": 75, "reserve0": 75, "ads": 0.45, "move": 0.83, "hip_spread": 0.019,
		"recoil_v": 0.019, "recoil_h": 0.013, "reload": 4.5, "ammo": "heavy",
		"mode": "auto", "pen": 1.4, "zoom": 0.0, "silent": false, "pitch": 0.75,
		"role": "Heavy 7.62 LMG. Slow, devastating, unstoppable.",
		"model": {"style": "heavy", "barrel": 0.56, "mag": "box", "stock": "fixed",
			"sight": "iron", "muzzle": "brake", "body": "grey", "accent": "wood", "extras": ["bipod", "carry"]}},
	# ------------------------------ SNIPERS (heavy) ------------------------------
	{"id": "lw9", "name": "LW-9", "alias": "Longeye", "cls": "sniper",
		"damage": 95, "rpm": 40, "range_near": 120.0, "range_far": 200.0,
		"mag": 5, "reserve0": 20, "ads": 0.45, "move": 0.88, "hip_spread": 0.06,
		"recoil_v": 0.05, "recoil_h": 0.02, "reload": 3.0, "ammo": "heavy",
		"mode": "bolt", "pen": 1.5, "zoom": 8.0, "silent": false, "pitch": 0.6,
		"role": "Heavy .50 bolt-action. One shot, one echo.",
		"model": {"style": "heavy", "barrel": 0.72, "mag": "straight", "stock": "fixed",
			"sight": "scopelong", "muzzle": "brake", "body": "od", "accent": "none", "extras": ["bipod"]}},
	{"id": "sr4", "name": "SR-4", "alias": "Falcon", "cls": "sniper",
		"damage": 80, "rpm": 50, "range_near": 100.0, "range_far": 180.0,
		"mag": 6, "reserve0": 24, "ads": 0.35, "move": 0.92, "hip_spread": 0.05,
		"recoil_v": 0.04, "recoil_h": 0.016, "reload": 2.6, "ammo": "heavy",
		"mode": "bolt", "pen": 1.3, "zoom": 6.0, "silent": false, "pitch": 0.7,
		"role": "Fast-handling scout sniper. Quickscope friendly.",
		"model": {"style": "scout", "barrel": 0.58, "mag": "internal", "stock": "skeleton",
			"sight": "scope", "muzzle": "flash", "body": "tan", "accent": "none", "extras": []}},
	{"id": "sr8", "name": "SR-8", "alias": "Reaper", "cls": "sniper",
		"damage": 65, "rpm": 120, "range_near": 90.0, "range_far": 160.0,
		"mag": 8, "reserve0": 32, "ads": 0.38, "move": 0.90, "hip_spread": 0.05,
		"recoil_v": 0.035, "recoil_h": 0.014, "reload": 2.8, "ammo": "heavy",
		"mode": "semi", "pen": 1.3, "zoom": 6.0, "silent": false, "pitch": 0.66,
		"role": "Semi-auto sniper. Follow-up shots on demand.",
		"model": {"style": "semi", "barrel": 0.62, "mag": "straight", "stock": "fixed",
			"sight": "scope", "muzzle": "brake", "body": "black", "accent": "none", "extras": []}},
	{"id": "am50", "name": "AM-50", "alias": "Titan", "cls": "sniper",
		"damage": 140, "rpm": 30, "range_near": 150.0, "range_far": 250.0,
		"mag": 4, "reserve0": 12, "ads": 0.55, "move": 0.82, "hip_spread": 0.07,
		"recoil_v": 0.07, "recoil_h": 0.025, "reload": 3.6, "ammo": "heavy",
		"mode": "bolt", "pen": 2.0, "zoom": 8.0, "silent": false, "pitch": 0.5,
		"role": "Anti-materiel monster. Deletes anything it touches.",
		"model": {"style": "antimat", "barrel": 0.80, "mag": "straight", "stock": "skeleton",
			"sight": "scopelong", "muzzle": "brake", "body": "grey", "accent": "none", "extras": ["bipod", "carry"]}},
	{"id": "vs12", "name": "VS-12", "alias": "Whisper", "cls": "sniper",
		"damage": 85, "rpm": 45, "range_near": 110.0, "range_far": 190.0,
		"mag": 5, "reserve0": 20, "ads": 0.40, "move": 0.89, "hip_spread": 0.05,
		"recoil_v": 0.038, "recoil_h": 0.015, "reload": 2.9, "ammo": "heavy",
		"mode": "bolt", "pen": 1.3, "zoom": 6.0, "silent": true, "pitch": 0.62,
		"role": "Suppressed bolt sniper. Death you never hear.",
		"model": {"style": "suppressed", "barrel": 0.60, "mag": "internal", "stock": "fixed",
			"sight": "scope", "muzzle": "suppressor", "body": "black", "accent": "none", "extras": []}},
	# ------------------------------ MARKSMAN (medium) ------------------------------
	{"id": "mk14", "name": "MK-14", "alias": "Lynx", "cls": "marksman",
		"damage": 55, "rpm": 180, "range_near": 60.0, "range_far": 110.0,
		"mag": 12, "reserve0": 48, "ads": 0.32, "move": 0.92, "hip_spread": 0.02,
		"recoil_v": 0.028, "recoil_h": 0.012, "reload": 2.2, "ammo": "medium",
		"mode": "semi", "pen": 1.2, "zoom": 4.0, "silent": false, "pitch": 0.82,
		"role": "Semi-auto precision. Two taps at range.",
		"model": {"style": "precision", "barrel": 0.54, "mag": "straight", "stock": "fixed",
			"sight": "scope", "muzzle": "flash", "body": "od", "accent": "wood", "extras": ["bipod"]}},
	{"id": "eb8", "name": "EB-8", "alias": "Eagle", "cls": "marksman",
		"damage": 60, "rpm": 160, "range_near": 65.0, "range_far": 120.0,
		"mag": 10, "reserve0": 40, "ads": 0.34, "move": 0.91, "hip_spread": 0.02,
		"recoil_v": 0.030, "recoil_h": 0.013, "reload": 2.4, "ammo": "medium",
		"mode": "semi", "pen": 1.3, "zoom": 4.0, "silent": false, "pitch": 0.78,
		"role": "Battle-rifle marksman. Heavy, deliberate, lethal.",
		"model": {"style": "battle", "barrel": 0.58, "mag": "straight", "stock": "fixed",
			"sight": "scope", "muzzle": "brake", "body": "tan", "accent": "none", "extras": []}},
	{"id": "cm5", "name": "CM-5", "alias": "Crosshair", "cls": "marksman",
		"damage": 48, "rpm": 220, "range_near": 55.0, "range_far": 100.0,
		"mag": 14, "reserve0": 56, "ads": 0.28, "move": 0.94, "hip_spread": 0.018,
		"recoil_v": 0.024, "recoil_h": 0.011, "reload": 2.0, "ammo": "medium",
		"mode": "semi", "pen": 1.1, "zoom": 4.0, "silent": false, "pitch": 0.88,
		"role": "Lightweight marksman carbine. Agile precision.",
		"model": {"style": "carbine", "barrel": 0.48, "mag": "curved", "stock": "skeleton",
			"sight": "scope", "muzzle": "flash", "body": "grey", "accent": "none", "extras": []}},
	# ------------------------------ SHOTGUNS (shell) ------------------------------
	{"id": "p12", "name": "P-12", "alias": "Judge", "cls": "shotgun",
		"damage": 9, "pellets": 8, "rpm": 70, "range_near": 10.0, "range_far": 22.0,
		"mag": 6, "reserve0": 24, "ads": 0.30, "move": 0.95, "hip_spread": 0.05,
		"recoil_v": 0.045, "recoil_h": 0.02, "reload": 2.6, "ammo": "shell",
		"mode": "pump", "pen": 0.5, "zoom": 0.0, "silent": false, "pitch": 0.7,
		"role": "Pump shotgun. The courtroom adjourns.",
		"model": {"style": "pump", "barrel": 0.46, "mag": "tube", "stock": "fixed",
			"sight": "iron", "muzzle": "none", "body": "black", "accent": "wood", "extras": ["heatshield"]}},
	{"id": "sa9", "name": "SA-9", "alias": "Riot", "cls": "shotgun",
		"damage": 8, "pellets": 8, "rpm": 140, "range_near": 10.0, "range_far": 22.0,
		"mag": 8, "reserve0": 32, "ads": 0.28, "move": 0.95, "hip_spread": 0.05,
		"recoil_v": 0.04, "recoil_h": 0.018, "reload": 2.4, "ammo": "shell",
		"mode": "semi", "pen": 0.5, "zoom": 0.0, "silent": false, "pitch": 0.75,
		"role": "Semi-auto shotgun. Room-clearing rhythm.",
		"model": {"style": "semi", "barrel": 0.44, "mag": "tube", "stock": "folding",
			"sight": "iron", "muzzle": "none", "body": "gunmetal", "accent": "none", "extras": []}},
	{"id": "db8", "name": "DB-8", "alias": "Diplomacy", "cls": "shotgun",
		"damage": 10, "pellets": 8, "rpm": 90, "range_near": 9.0, "range_far": 20.0,
		"mag": 2, "reserve0": 20, "ads": 0.26, "move": 0.97, "hip_spread": 0.05,
		"recoil_v": 0.05, "recoil_h": 0.022, "reload": 2.2, "ammo": "shell",
		"mode": "semi", "pen": 0.5, "zoom": 0.0, "silent": false, "pitch": 0.65,
		"role": "Double-barrel. Two negotiations, both final.",
		"model": {"style": "double", "barrel": 0.50, "mag": "none", "stock": "fixed",
			"sight": "iron", "muzzle": "none", "body": "gunmetal", "accent": "wood", "extras": []}},
	{"id": "df12", "name": "DF-12", "alias": "Drummer", "cls": "shotgun",
		"damage": 7, "pellets": 8, "rpm": 220, "range_near": 10.0, "range_far": 22.0,
		"mag": 20, "reserve0": 40, "ads": 0.30, "move": 0.94, "hip_spread": 0.05,
		"recoil_v": 0.035, "recoil_h": 0.018, "reload": 3.0, "ammo": "shell",
		"mode": "auto", "pen": 0.5, "zoom": 0.0, "silent": false, "pitch": 0.8,
		"role": "Drum-fed auto shotgun. Sustained thunder.",
		"model": {"style": "auto", "barrel": 0.42, "mag": "drum", "stock": "skeleton",
			"sight": "reddot", "muzzle": "none", "body": "black", "accent": "none", "extras": []}},
	{"id": "sp4", "name": "SP-4", "alias": "Sweeper", "cls": "shotgun",
		"damage": 11, "pellets": 6, "rpm": 60, "range_near": 11.0, "range_far": 24.0,
		"mag": 5, "reserve0": 20, "ads": 0.32, "move": 0.93, "hip_spread": 0.055,
		"recoil_v": 0.055, "recoil_h": 0.024, "reload": 2.8, "ammo": "shell",
		"mode": "pump", "pen": 0.6, "zoom": 0.0, "silent": false, "pitch": 0.6,
		"role": "Heavy pump. Fewer pellets, each one a verdict.",
		"model": {"style": "heavy", "barrel": 0.52, "mag": "tube", "stock": "fixed",
			"sight": "iron", "muzzle": "brake", "body": "od", "accent": "none", "extras": ["heatshield"]}},
	# ------------------------------- PISTOLS (light) -------------------------------
	{"id": "p9", "name": "P9", "alias": "Sidekick", "cls": "pistol",
		"damage": 22, "rpm": 400, "range_near": 18.0, "range_far": 40.0,
		"mag": 15, "reserve0": 60, "ads": 0.18, "move": 1.03, "hip_spread": 0.012,
		"recoil_v": 0.012, "recoil_h": 0.010, "reload": 1.4, "ammo": "light",
		"mode": "semi", "pen": 0.6, "zoom": 0.0, "silent": false, "pitch": 1.25,
		"role": "Standard 9mm sidearm. Always there when needed.",
		"model": {"style": "service", "barrel": 0.12, "mag": "stick", "stock": "none",
			"sight": "iron", "muzzle": "none", "body": "black", "accent": "none", "extras": []}},
	{"id": "mp50", "name": "MP-50", "alias": "Pocketstorm", "cls": "pistol",
		"damage": 18, "rpm": 900, "range_near": 14.0, "range_far": 30.0,
		"mag": 24, "reserve0": 96, "ads": 0.18, "move": 1.03, "hip_spread": 0.014,
		"recoil_v": 0.010, "recoil_h": 0.011, "reload": 1.6, "ammo": "light",
		"mode": "auto", "pen": 0.5, "zoom": 0.0, "silent": false, "pitch": 1.35,
		"role": "Machine pistol. A storm in your pocket.",
		"model": {"style": "machine", "barrel": 0.14, "mag": "stick", "stock": "wire",
			"sight": "iron", "muzzle": "comp", "body": "grey", "accent": "none", "extras": []}},
	{"id": "d50", "name": "D-50", "alias": "Handcannon", "cls": "pistol",
		"damage": 55, "rpm": 200, "range_near": 24.0, "range_far": 50.0,
		"mag": 7, "reserve0": 28, "ads": 0.24, "move": 1.0, "hip_spread": 0.014,
		"recoil_v": 0.030, "recoil_h": 0.016, "reload": 1.9, "ammo": "light",
		"mode": "semi", "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 0.7,
		"role": "Heavy .50 pistol. Handheld artillery.",
		"model": {"style": "heavy", "barrel": 0.16, "mag": "stick", "stock": "none",
			"sight": "iron", "muzzle": "brake", "body": "gunmetal", "accent": "none", "extras": []}},
	{"id": "s9", "name": "S9", "alias": "Silent", "cls": "pistol",
		"damage": 20, "rpm": 380, "range_near": 16.0, "range_far": 36.0,
		"mag": 12, "reserve0": 48, "ads": 0.18, "move": 1.03, "hip_spread": 0.012,
		"recoil_v": 0.010, "recoil_h": 0.009, "reload": 1.5, "ammo": "light",
		"mode": "semi", "pen": 0.5, "zoom": 0.0, "silent": true, "pitch": 1.1,
		"role": "Suppressed pistol. Polite, final.",
		"model": {"style": "suppressed", "barrel": 0.13, "mag": "stick", "stock": "none",
			"sight": "iron", "muzzle": "suppressor", "body": "black", "accent": "none", "extras": []}},
	# -------------------------------- MELEE (none) --------------------------------
	{"id": "knife", "name": "Fang", "alias": "Knife", "cls": "melee",
		"damage": 55, "rpm": 100, "range_near": 2.2, "range_far": 2.2,
		"mag": 1, "reserve0": 0, "ads": 0.12, "move": 1.06, "hip_spread": 0.0,
		"recoil_v": 0.0, "recoil_h": 0.0, "reload": 0.5, "ammo": "none",
		"mode": "melee", "pen": 0.0, "zoom": 0.0, "silent": true, "pitch": 1.0,
		"role": "Combat knife. Fast, silent, personal.",
		"model": {"style": "knife", "barrel": 0.0, "mag": "none", "stock": "none",
			"sight": "none", "muzzle": "none", "body": "black", "accent": "none", "extras": []}},
	{"id": "axe", "name": "Cleaver", "alias": "Axe", "cls": "melee",
		"damage": 80, "rpm": 70, "range_near": 2.3, "range_far": 2.3,
		"mag": 1, "reserve0": 0, "ads": 0.14, "move": 1.04, "hip_spread": 0.0,
		"recoil_v": 0.0, "recoil_h": 0.0, "reload": 0.6, "ammo": "none",
		"mode": "melee", "pen": 0.0, "zoom": 0.0, "silent": true, "pitch": 0.9,
		"role": "Tactical axe. Heavy overhead justice.",
		"model": {"style": "axe", "barrel": 0.0, "mag": "none", "stock": "none",
			"sight": "none", "muzzle": "none", "body": "black", "accent": "wood", "extras": []}},
	{"id": "katana", "name": "Ronin", "alias": "Katana", "cls": "melee",
		"damage": 70, "range_near": 2.6, "range_far": 2.6, "rpm": 85,
		"mag": 1, "reserve0": 0, "ads": 0.13, "move": 1.05, "hip_spread": 0.0,
		"recoil_v": 0.0, "recoil_h": 0.0, "reload": 0.55, "ammo": "none",
		"mode": "melee", "pen": 0.0, "zoom": 0.0, "silent": true, "pitch": 1.05,
		"role": "Katana. Long reach, flowing cuts.",
		"model": {"style": "katana", "barrel": 0.0, "mag": "none", "stock": "none",
			"sight": "none", "muzzle": "none", "body": "black", "accent": "none", "extras": []}},
	# ------------------------------ LAUNCHERS ------------------------------
	{"id": "rl4", "name": "RL-4", "alias": "Sledge", "cls": "launcher",
		"damage": 120, "rpm": 40, "range_near": 60.0, "range_far": 120.0,
		"mag": 1, "reserve0": 3, "ads": 0.40, "move": 0.88, "hip_spread": 0.02,
		"recoil_v": 0.04, "recoil_h": 0.01, "reload": 2.8, "ammo": "rocket",
		"mode": "rocket", "pen": 0.0, "zoom": 0.0, "silent": false, "pitch": 0.55,
		"blast": 4.5, "proj_speed": 42.0, "proj_grav": 0.15,
		"role": "Rocket launcher. Dumbfire demolition.",
		"model": {"style": "rpg", "barrel": 0.0, "mag": "none", "stock": "none",
			"sight": "iron", "muzzle": "none", "body": "od", "accent": "wood", "extras": []}},
	{"id": "gl6", "name": "GL-6", "alias": "Thumper", "cls": "launcher",
		"damage": 90, "rpm": 60, "range_near": 40.0, "range_far": 90.0,
		"mag": 6, "reserve0": 6, "ads": 0.34, "move": 0.92, "hip_spread": 0.02,
		"recoil_v": 0.03, "recoil_h": 0.01, "reload": 2.6, "ammo": "grenade",
		"mode": "grenade", "pen": 0.0, "zoom": 0.0, "silent": false, "pitch": 0.62,
		"blast": 3.5, "proj_speed": 26.0, "proj_grav": 1.0,
		"role": "Grenade launcher. Arcing area denial.",
		"model": {"style": "glauncher", "barrel": 0.34, "mag": "tube", "stock": "fixed",
			"sight": "iron", "muzzle": "none", "body": "black", "accent": "wood", "extras": []}},
	# ----------------- ASSAULT RIFLES: expansion (CODM research) -----------------
	{"id": "ax9", "name": "AX-9", "alias": "Raptor", "cls": "ar",
		"damage": 27, "rpm": 750, "range_near": 28.0, "range_far": 58.0,
		"mag": 30, "reserve0": 120, "ads": 0.25, "move": 0.95, "hip_spread": 0.013,
		"recoil_v": 0.015, "recoil_h": 0.011, "reload": 2.0, "ammo": "medium",
		"mode": "auto", "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 1.08,
		"sound": {"crack": 1.1}, "role": "Futuristic AK bullet hose. Aggressive and fast.",
		"model": {"style": "modular", "barrel": 0.40, "mag": "curved", "stock": "skeleton",
			"sight": "iron", "muzzle": "flash", "body": "graphite", "accent": "none", "extras": [], "receiver": "angular"}},
	{"id": "tp25", "name": "TP-25", "alias": "Cicada", "cls": "ar",
		"damage": 25, "rpm": 850, "range_near": 22.0, "range_far": 48.0,
		"mag": 30, "reserve0": 120, "ads": 0.22, "move": 0.97, "hip_spread": 0.015,
		"recoil_v": 0.014, "recoil_h": 0.013, "reload": 1.9, "ammo": "medium",
		"mode": "auto", "pen": 0.9, "zoom": 0.0, "silent": false, "pitch": 1.18,
		"sound": {"crack": 1.25, "dur": 0.85}, "role": "Wasp-like close-range hose. Fastest handling.",
		"model": {"style": "shredder", "barrel": 0.32, "mag": "curved", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "black", "accent": "none", "extras": ["foregrip"], "receiver": "angular"}},
	{"id": "am10", "name": "AM-10", "alias": "Longshot", "cls": "ar",
		"damage": 34, "rpm": 600, "range_near": 38.0, "range_far": 78.0,
		"mag": 30, "reserve0": 120, "ads": 0.30, "move": 0.92, "hip_spread": 0.013,
		"recoil_v": 0.017, "recoil_h": 0.010, "reload": 2.2, "ammo": "medium",
		"mode": "auto", "pen": 1.1, "zoom": 0.0, "silent": false, "pitch": 0.95,
		"role": "Long-range precision AR. Canted mag, huge reach.",
		"model": {"style": "precision", "barrel": 0.52, "mag": "curved", "stock": "thumbhole",
			"sight": "iron", "muzzle": "brake", "body": "tan", "accent": "wood", "extras": []}},
	{"id": "bk57", "name": "BK-57", "alias": "Brick", "cls": "ar",
		"damage": 29, "rpm": 650, "range_near": 30.0, "range_far": 62.0,
		"mag": 30, "reserve0": 120, "ads": 0.27, "move": 0.94, "hip_spread": 0.013,
		"recoil_v": 0.015, "recoil_h": 0.010, "reload": 2.0, "ammo": "medium",
		"mode": "auto", "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 1.0,
		"sound": {"body": 0.9}, "role": "Forgiving mid-range workhorse. Boxy and dependable.",
		"model": {"style": "modular", "barrel": 0.38, "mag": "curved", "stock": "wire",
			"sight": "iron", "muzzle": "flash", "body": "grey", "accent": "none", "extras": [], "receiver": "boxy"}},
	{"id": "lk24", "name": "LK-24", "alias": "Specter", "cls": "ar",
		"damage": 28, "rpm": 700, "range_near": 28.0, "range_far": 60.0,
		"mag": 30, "reserve0": 120, "ads": 0.24, "move": 0.96, "hip_spread": 0.013,
		"recoil_v": 0.014, "recoil_h": 0.011, "reload": 1.9, "ammo": "medium",
		"mode": "auto", "pen": 0.95, "zoom": 0.0, "silent": false, "pitch": 1.06,
		"role": "Mobile mid-range AR. Signature see-through magazine.",
		"model": {"style": "compact", "barrel": 0.34, "mag": "casket", "stock": "skeleton",
			"sight": "iron", "muzzle": "flash", "body": "graphite", "accent": "none", "extras": [], "carry_handle": true}},
	{"id": "ic1", "name": "IC-1", "alias": "Lowpro", "cls": "ar",
		"damage": 27, "rpm": 650, "range_near": 30.0, "range_far": 64.0,
		"mag": 30, "reserve0": 120, "ads": 0.26, "move": 0.95, "hip_spread": 0.011,
		"recoil_v": 0.012, "recoil_h": 0.009, "reload": 2.0, "ammo": "medium",
		"mode": "auto", "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 1.02,
		"sound": {"crack": 0.9, "thump": 0.8}, "role": "Low-recoil laser. Beginner-friendly beam.",
		"model": {"style": "advanced", "barrel": 0.38, "mag": "curved", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "white", "accent": "none", "extras": [], "receiver": "slim"}},
	{"id": "hb3", "name": "HB-3", "alias": "Metronome", "cls": "ar",
		"damage": 29, "rpm": 700, "range_near": 32.0, "range_far": 66.0,
		"mag": 30, "reserve0": 120, "ads": 0.27, "move": 0.94, "hip_spread": 0.012,
		"recoil_v": 0.014, "recoil_h": 0.009, "reload": 2.0, "ammo": "medium",
		"mode": "auto", "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 1.0,
		"role": "Steady and controllable. Metronome cadence at mid-long range.",
		"model": {"style": "modular", "barrel": 0.40, "mag": "curved", "stock": "folding",
			"sight": "acog", "muzzle": "flash", "body": "black", "accent": "none", "extras": []}},
	{"id": "kn44", "name": "KN-44", "alias": "Growler", "cls": "ar",
		"damage": 31, "rpm": 700, "range_near": 30.0, "range_far": 62.0,
		"mag": 30, "reserve0": 120, "ads": 0.27, "move": 0.94, "hip_spread": 0.013,
		"recoil_v": 0.016, "recoil_h": 0.011, "reload": 2.1, "ammo": "medium",
		"mode": "auto", "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 0.98,
		"sound": {"thump": 1.2}, "role": "AK growl, modern crispness. Aggressive mid-range.",
		"model": {"style": "piston", "barrel": 0.42, "mag": "curved", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "gunmetal", "accent": "none", "extras": []}},
	{"id": "hv30", "name": "HV-30", "alias": "Scalpel", "cls": "ar",
		"damage": 28, "rpm": 700, "range_near": 32.0, "range_far": 68.0,
		"mag": 30, "reserve0": 120, "ads": 0.26, "move": 0.95, "hip_spread": 0.011,
		"recoil_v": 0.013, "recoil_h": 0.009, "reload": 2.0, "ammo": "medium",
		"mode": "auto", "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 1.02,
		"role": "Precision instrument. Rewards aim discipline.",
		"model": {"style": "precision", "barrel": 0.40, "mag": "curved", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "graphite", "accent": "none", "extras": [], "receiver": "slim"}},
	{"id": "drh", "name": "DR-H", "alias": "Mauler", "cls": "ar",
		"damage": 40, "rpm": 550, "range_near": 36.0, "range_far": 74.0,
		"mag": 20, "reserve0": 80, "ads": 0.31, "move": 0.91, "hip_spread": 0.015,
		"recoil_v": 0.020, "recoil_h": 0.012, "reload": 2.3, "ammo": "medium",
		"mode": "auto", "pen": 1.2, "zoom": 0.0, "silent": false, "pitch": 0.85,
		"sound": {"thump": 1.4, "crack": 0.85}, "role": "Heavy battle rifle. Each shot a punch.",
		"model": {"style": "battle", "barrel": 0.46, "mag": "curved", "stock": "folding",
			"sight": "iron", "muzzle": "brake", "body": "tan", "accent": "none", "extras": [], "receiver": "boxy"}},
	{"id": "pk2", "name": "PK-2", "alias": "Doubletap", "cls": "ar",
		"damage": 32, "rpm": 600, "range_near": 26.0, "range_far": 56.0,
		"mag": 30, "reserve0": 120, "ads": 0.24, "move": 0.96, "hip_spread": 0.013,
		"recoil_v": 0.014, "recoil_h": 0.011, "reload": 1.9, "ammo": "medium",
		"mode": "burst", "burst_n": 2, "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 1.1,
		"role": "2-round burst hybrid. SMG handling, rifle damage.",
		"model": {"style": "compact", "barrel": 0.32, "mag": "curved", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "bluegrey", "accent": "none", "extras": [], "receiver": "slim"}},
	{"id": "fr55", "name": "FR-55", "alias": "Musketeer", "cls": "ar",
		"damage": 33, "rpm": 650, "range_near": 34.0, "range_far": 70.0,
		"mag": 30, "reserve0": 120, "ads": 0.28, "move": 0.93, "hip_spread": 0.012,
		"recoil_v": 0.015, "recoil_h": 0.010, "reload": 2.1, "ammo": "medium",
		"mode": "burst", "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 1.0,
		"role": "Burst bullpup. Iconic carry handle, extreme range accuracy.",
		"model": {"style": "bullpup", "barrel": 0.44, "mag": "straight", "stock": "bullpup",
			"sight": "iron", "muzzle": "flash", "body": "grey", "accent": "none", "extras": ["bipod"], "carry_handle": true}},
	{"id": "av9", "name": "AV-9", "alias": "Nightshade", "cls": "ar",
		"damage": 28, "rpm": 800, "range_near": 20.0, "range_far": 42.0,
		"mag": 20, "reserve0": 100, "ads": 0.24, "move": 0.96, "hip_spread": 0.014,
		"recoil_v": 0.013, "recoil_h": 0.011, "reload": 2.1, "ammo": "medium",
		"mode": "auto", "pen": 0.9, "zoom": 0.0, "silent": true, "pitch": 0.9,
		"role": "Integrally suppressed shredder. Death whispers.",
		"model": {"style": "stealth", "barrel": 0.30, "mag": "curved", "stock": "wire",
			"sight": "iron", "muzzle": "shroud", "body": "black", "accent": "none", "extras": [], "receiver": "slim"}},
	{"id": "m13", "name": "M-13", "alias": "Rattler", "cls": "ar",
		"damage": 24, "rpm": 850, "range_near": 24.0, "range_far": 52.0,
		"mag": 30, "reserve0": 120, "ads": 0.23, "move": 0.96, "hip_spread": 0.014,
		"recoil_v": 0.013, "recoil_h": 0.012, "reload": 1.9, "ammo": "medium",
		"mode": "auto", "pen": 0.9, "zoom": 0.0, "silent": false, "pitch": 1.15,
		"sound": {"crack": 1.15, "dur": 0.85}, "role": "High-RPM bullet hose. Overwhelming fire rate.",
		"model": {"style": "shredder", "barrel": 0.32, "mag": "curved", "stock": "skeleton",
			"sight": "iron", "muzzle": "flash", "body": "black", "accent": "none", "extras": [], "receiver": "slim"}},
	{"id": "sf4", "name": "SF-4", "alias": "Broadbill", "cls": "ar",
		"damage": 27, "rpm": 600, "range_near": 34.0, "range_far": 72.0,
		"mag": 40, "reserve0": 120, "ads": 0.29, "move": 0.93, "hip_spread": 0.012,
		"recoil_v": 0.014, "recoil_h": 0.010, "reload": 2.3, "ammo": "medium",
		"mode": "burst", "burst_n": 4, "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 0.92,
		"sound": {"thump": 1.2}, "role": "4-round burst long rifle. Burst precision, huge mag.",
		"model": {"style": "burst", "barrel": 0.50, "mag": "casket", "stock": "thumbhole",
			"sight": "acog", "muzzle": "shroud", "body": "graphite", "accent": "none", "extras": [], "receiver": "angular"}},
	{"id": "k141", "name": "K-141", "alias": "Paragon", "cls": "ar",
		"damage": 28, "rpm": 750, "range_near": 32.0, "range_far": 68.0,
		"mag": 30, "reserve0": 120, "ads": 0.25, "move": 0.95, "hip_spread": 0.011,
		"recoil_v": 0.012, "recoil_h": 0.009, "reload": 2.0, "ammo": "medium",
		"mode": "auto", "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 1.04,
		"role": "The accuracy benchmark. Meta low-recoil laser.",
		"model": {"style": "advanced", "barrel": 0.38, "mag": "curved", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "grey", "accent": "none", "extras": [], "receiver": "angular"}},
	{"id": "od12", "name": "OD-12", "alias": "Mammoth", "cls": "ar",
		"damage": 48, "rpm": 400, "range_near": 40.0, "range_far": 80.0,
		"mag": 20, "reserve0": 80, "ads": 0.33, "move": 0.90, "hip_spread": 0.016,
		"recoil_v": 0.024, "recoil_h": 0.014, "reload": 2.5, "ammo": "medium",
		"mode": "auto", "pen": 1.3, "zoom": 0.0, "silent": false, "pitch": 0.78,
		"sound": {"thump": 1.6, "crack": 0.7, "dur": 1.2}, "role": "Oversized battle rifle. Each shot a small cannon.",
		"model": {"style": "battle", "barrel": 0.50, "mag": "straight", "stock": "fixed",
			"sight": "iron", "muzzle": "brake", "body": "od", "accent": "none", "extras": [], "receiver": "boxy"}},
	{"id": "kg6", "name": "KG-6", "alias": "Workhorse", "cls": "ar",
		"damage": 29, "rpm": 700, "range_near": 32.0, "range_far": 66.0,
		"mag": 30, "reserve0": 120, "ads": 0.26, "move": 0.95, "hip_spread": 0.012,
		"recoil_v": 0.013, "recoil_h": 0.009, "reload": 2.0, "ammo": "medium",
		"mode": "auto", "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 1.0,
		"role": "Dependable all-rounder. Top-tier control.",
		"model": {"style": "modular", "barrel": 0.40, "mag": "curved", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "od", "accent": "none", "extras": []}},
	{"id": "em2", "name": "EM-2", "alias": "Britannia", "cls": "ar",
		"damage": 38, "rpm": 500, "range_near": 36.0, "range_far": 74.0,
		"mag": 25, "reserve0": 100, "ads": 0.30, "move": 0.92, "hip_spread": 0.014,
		"recoil_v": 0.019, "recoil_h": 0.011, "reload": 2.2, "ammo": "medium",
		"mode": "auto", "pen": 1.1, "zoom": 0.0, "silent": false, "pitch": 0.85,
		"sound": {"thump": 1.3}, "role": "Retro bullpup. Slow, heavy, unmistakable.",
		"model": {"style": "bullpup", "barrel": 0.46, "mag": "curved", "stock": "bullpup",
			"sight": "acog", "muzzle": "flash", "body": "bronze", "accent": "wood", "extras": []}},
	{"id": "mdx9", "name": "MDX-9", "alias": "Echofire", "cls": "ar",
		"damage": 26, "rpm": 720, "range_near": 26.0, "range_far": 56.0,
		"mag": 30, "reserve0": 120, "ads": 0.23, "move": 0.97, "hip_spread": 0.013,
		"recoil_v": 0.014, "recoil_h": 0.012, "reload": 1.9, "ammo": "medium",
		"mode": "auto", "pen": 0.9, "zoom": 0.0, "silent": false, "pitch": 1.12,
		"sound": {"crack": 1.1}, "role": "Fastest-handling bullpup. Close-range aggressor.",
		"model": {"style": "bullpup", "barrel": 0.36, "mag": "curved", "stock": "bullpup",
			"sight": "reddot", "muzzle": "flash", "body": "bluegrey", "accent": "none", "extras": [], "receiver": "angular"}},
	{"id": "ff1", "name": "FF-1", "alias": "Frenzy", "cls": "ar",
		"damage": 24, "rpm": 900, "range_near": 20.0, "range_far": 44.0,
		"mag": 25, "reserve0": 125, "ads": 0.22, "move": 0.97, "hip_spread": 0.016,
		"recoil_v": 0.015, "recoil_h": 0.014, "reload": 2.0, "ammo": "medium",
		"mode": "auto", "pen": 0.9, "zoom": 0.0, "silent": false, "pitch": 1.2,
		"sound": {"crack": 1.25, "dur": 0.8}, "role": "900 RPM buzzsaw. Melts up close, wild kick.",
		"model": {"style": "bullpup", "barrel": 0.40, "mag": "straight", "stock": "bullpup",
			"sight": "iron", "muzzle": "flash", "body": "grey", "accent": "none", "extras": [], "carry_handle": true}},
	{"id": "gr56", "name": "GR-56", "alias": "Needle", "cls": "ar",
		"damage": 27, "rpm": 750, "range_near": 36.0, "range_far": 76.0,
		"mag": 30, "reserve0": 120, "ads": 0.25, "move": 0.95, "hip_spread": 0.010,
		"recoil_v": 0.011, "recoil_h": 0.008, "reload": 2.0, "ammo": "medium",
		"mode": "auto", "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 1.06,
		"role": "Long-range laser. Near-zero recoil, clean sightline.",
		"model": {"style": "precision", "barrel": 0.44, "mag": "curved", "stock": "folding",
			"sight": "iron", "muzzle": "linear", "body": "graphite", "accent": "none", "extras": [], "receiver": "slim"}},
	{"id": "gz9", "name": "GZ-9", "alias": "Ogre", "cls": "ar",
		"damage": 32, "rpm": 700, "range_near": 28.0, "range_far": 60.0,
		"mag": 30, "reserve0": 120, "ads": 0.26, "move": 0.94, "hip_spread": 0.014,
		"recoil_v": 0.016, "recoil_h": 0.012, "reload": 2.1, "ammo": "medium",
		"mode": "auto", "pen": 1.0, "zoom": 0.0, "silent": false, "pitch": 0.95,
		"sound": {"thump": 1.2, "crack": 0.9}, "role": "Hard-hitting compact bullpup. Intimidating profile.",
		"model": {"style": "bullpup", "barrel": 0.34, "mag": "curved", "stock": "bullpup",
			"sight": "iron", "muzzle": "shroud", "body": "od", "accent": "none", "extras": [], "receiver": "boxy"}},
	# ------------------ LMGs: expansion (CODM research) ------------------
	{"id": "rd7", "name": "RD-7", "alias": "Drumroll", "cls": "lmg",
		"damage": 31, "rpm": 650, "range_near": 34.0, "range_far": 70.0,
		"mag": 100, "reserve0": 100, "ads": 0.40, "move": 0.86, "hip_spread": 0.017,
		"recoil_v": 0.016, "recoil_h": 0.012, "reload": 4.0, "ammo": "heavy",
		"mode": "auto", "pen": 1.3, "zoom": 0.0, "silent": false, "pitch": 0.82,
		"sound": {"thump": 1.3}, "role": "Sustained-fire anchor. Rolling dugga-dugga.",
		"model": {"style": "belt", "barrel": 0.54, "mag": "drum", "stock": "fixed",
			"sight": "iron", "muzzle": "brake", "body": "gunmetal", "accent": "wood", "extras": ["bipod", "carry"]}},
	{"id": "ul7", "name": "UL-7", "alias": "Longbow", "cls": "lmg",
		"damage": 30, "rpm": 600, "range_near": 38.0, "range_far": 78.0,
		"mag": 100, "reserve0": 100, "ads": 0.40, "move": 0.86, "hip_spread": 0.015,
		"recoil_v": 0.014, "recoil_h": 0.010, "reload": 4.0, "ammo": "heavy",
		"mode": "auto", "pen": 1.3, "zoom": 0.0, "silent": false, "pitch": 0.85,
		"role": "Long-range LMG. Sustained precision fire.",
		"model": {"style": "light", "barrel": 0.60, "mag": "drum", "stock": "fixed",
			"sight": "acog", "muzzle": "flash", "body": "od", "accent": "none", "extras": ["bipod"]}},
	{"id": "s36", "name": "S-36", "alias": "Tempest", "cls": "lmg",
		"damage": 29, "rpm": 750, "range_near": 30.0, "range_far": 62.0,
		"mag": 100, "reserve0": 100, "ads": 0.36, "move": 0.88, "hip_spread": 0.018,
		"recoil_v": 0.017, "recoil_h": 0.014, "reload": 3.8, "ammo": "heavy",
		"mode": "auto", "pen": 1.2, "zoom": 0.0, "silent": false, "pitch": 0.9,
		"sound": {"crack": 1.1}, "role": "Fastest LMG bullet hose. Tame the recoil.",
		"model": {"style": "light", "barrel": 0.46, "mag": "drum", "stock": "skeleton",
			"sight": "iron", "muzzle": "comp", "body": "tan", "accent": "none", "extras": ["foregrip"]}},
	{"id": "ch9", "name": "CH-9", "alias": "Chainsaw", "cls": "lmg",
		"damage": 28, "rpm": 750, "range_near": 22.0, "range_far": 48.0,
		"mag": 90, "reserve0": 90, "ads": 0.38, "move": 0.90, "hip_spread": 0.014,
		"recoil_v": 0.015, "recoil_h": 0.013, "reload": 3.6, "ammo": "heavy",
		"mode": "auto", "pen": 1.1, "zoom": 0.0, "silent": false, "pitch": 0.88,
		"sound": {"thump": 1.2}, "role": "No-stock hip-fire terror. Chainsaw handling.",
		"model": {"style": "belt", "barrel": 0.40, "mag": "belt", "stock": "none",
			"sight": "iron", "muzzle": "shroud", "body": "black", "accent": "none", "extras": ["heatshield"]}},
	{"id": "hg26", "name": "HG-26", "alias": "Backbone", "cls": "lmg",
		"damage": 30, "rpm": 700, "range_near": 32.0, "range_far": 66.0,
		"mag": 100, "reserve0": 100, "ads": 0.36, "move": 0.88, "hip_spread": 0.015,
		"recoil_v": 0.014, "recoil_h": 0.010, "reload": 3.6, "ammo": "heavy",
		"mode": "auto", "pen": 1.2, "zoom": 0.0, "silent": false, "pitch": 0.88,
		"role": "Best all-round LMG. Low recoil, dependable.",
		"model": {"style": "box", "barrel": 0.48, "mag": "drum", "stock": "skeleton",
			"sight": "iron", "muzzle": "flash", "body": "black", "accent": "none", "extras": ["bipod"], "carry_handle": true}},
	{"id": "hd6", "name": "HD-6", "alias": "Furnace", "cls": "lmg",
		"damage": 34, "rpm": 600, "range_near": 32.0, "range_far": 66.0,
		"mag": 80, "reserve0": 80, "ads": 0.38, "move": 0.87, "hip_spread": 0.016,
		"recoil_v": 0.016, "recoil_h": 0.011, "reload": 3.8, "ammo": "heavy",
		"mode": "auto", "pen": 1.3, "zoom": 0.0, "silent": false, "pitch": 0.82,
		"sound": {"thump": 1.4}, "role": "Hard-hitting compact LMG. Mid-range brawler.",
		"model": {"style": "box", "barrel": 0.42, "mag": "box", "stock": "folding",
			"sight": "iron", "muzzle": "brake", "body": "graphite", "accent": "none", "extras": [], "receiver": "angular"}},
	{"id": "bn9", "name": "BN-9", "alias": "Avalanche", "cls": "lmg",
		"damage": 31, "rpm": 650, "range_near": 34.0, "range_far": 72.0,
		"mag": 100, "reserve0": 100, "ads": 0.40, "move": 0.86, "hip_spread": 0.016,
		"recoil_v": 0.015, "recoil_h": 0.011, "reload": 4.0, "ammo": "heavy",
		"mode": "auto", "pen": 1.3, "zoom": 0.0, "silent": false, "pitch": 0.84,
		"sound": {"thump": 1.3}, "role": "Rolling thunder. Area control, huge suppression.",
		"model": {"style": "belt", "barrel": 0.50, "mag": "belt", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "tan", "accent": "none", "extras": ["bipod"]}},
	{"id": "mg42", "name": "MG-42", "alias": "Ripsaw", "cls": "lmg",
		"damage": 26, "rpm": 1150, "range_near": 24.0, "range_far": 52.0,
		"mag": 75, "reserve0": 75, "ads": 0.38, "move": 0.88, "hip_spread": 0.019,
		"recoil_v": 0.016, "recoil_h": 0.015, "reload": 3.8, "ammo": "heavy",
		"mode": "auto", "pen": 1.1, "zoom": 0.0, "silent": false, "pitch": 1.0,
		"sound": {"crack": 1.3, "dur": 0.8}, "role": "Legendary buzzsaw. Fastest gun in the game.",
		"model": {"style": "belt", "barrel": 0.48, "mag": "drum", "stock": "fixed",
			"sight": "iron", "muzzle": "brake", "body": "gunmetal", "accent": "wood", "extras": ["bipod"]}},
	{"id": "rl7", "name": "RL-7", "alias": "Monolith", "cls": "lmg",
		"damage": 33, "rpm": 500, "range_near": 36.0, "range_far": 76.0,
		"mag": 75, "reserve0": 75, "ads": 0.42, "move": 0.85, "hip_spread": 0.014,
		"recoil_v": 0.013, "recoil_h": 0.009, "reload": 4.2, "ammo": "heavy",
		"mode": "auto", "pen": 1.4, "zoom": 0.0, "silent": false, "pitch": 0.8,
		"sound": {"thump": 1.4}, "role": "Titan-like and easy to control. Long-range sustained.",
		"model": {"style": "heavy", "barrel": 0.56, "mag": "belt", "stock": "fixed",
			"sight": "iron", "muzzle": "brake", "body": "grey", "accent": "none", "extras": ["bipod"], "receiver": "boxy"}},
	{"id": "mg82", "name": "MG-82", "alias": "Sprinter", "cls": "lmg",
		"damage": 29, "rpm": 800, "range_near": 30.0, "range_far": 64.0,
		"mag": 100, "reserve0": 100, "ads": 0.36, "move": 0.89, "hip_spread": 0.016,
		"recoil_v": 0.014, "recoil_h": 0.011, "reload": 3.6, "ammo": "heavy",
		"mode": "auto", "pen": 1.2, "zoom": 0.0, "silent": false, "pitch": 0.92,
		"role": "Fast and accurate. High tempo with control.",
		"model": {"style": "light", "barrel": 0.44, "mag": "box", "stock": "folding",
			"sight": "iron", "muzzle": "comp", "body": "od", "accent": "none", "extras": [], "carry_handle": true}},
	{"id": "dp27", "name": "DP-27", "alias": "Panhead", "cls": "lmg",
		"damage": 33, "rpm": 550, "range_near": 34.0, "range_far": 70.0,
		"mag": 47, "reserve0": 94, "ads": 0.40, "move": 0.86, "hip_spread": 0.017,
		"recoil_v": 0.016, "recoil_h": 0.011, "reload": 4.4, "ammo": "heavy",
		"mode": "auto", "pen": 1.3, "zoom": 0.0, "silent": false, "pitch": 0.8,
		"sound": {"thump": 1.2}, "role": "Iconic top pan magazine. Slow, hard, rhythmic.",
		"model": {"style": "surplus", "barrel": 0.56, "mag": "pan", "stock": "fixed",
			"sight": "iron", "muzzle": "flash", "body": "gunmetal", "accent": "wood", "extras": ["bipod"], "toprail": false}},
	# ----------------- Snipers: expansion (CODM research) -----------------
	{"id": "dq33", "name": "DQ-33", "alias": "Icon", "cls": "sniper",
		"damage": 95, "rpm": 42, "range_near": 120.0, "range_far": 200.0,
		"mag": 5, "reserve0": 20, "ads": 0.42, "move": 0.89, "hip_spread": 0.055,
		"recoil_v": 0.048, "recoil_h": 0.018, "reload": 2.9, "ammo": "heavy",
		"mode": "bolt", "pen": 1.5, "zoom": 8.0, "silent": false, "pitch": 0.62,
		"sound": {"crack": 1.1, "dur": 1.1}, "role": "The iconic one-shot bolt-action. Whip-crack boom.",
		"model": {"style": "heavy", "barrel": 0.70, "mag": "straight", "stock": "skeleton",
			"sight": "scopelong", "muzzle": "brake", "body": "tan", "accent": "none", "extras": ["bipod"], "carry_handle": true}},
	{"id": "eb21", "name": "EB-21", "alias": "Bedrock", "cls": "sniper",
		"damage": 62, "rpm": 130, "range_near": 90.0, "range_far": 160.0,
		"mag": 10, "reserve0": 40, "ads": 0.36, "move": 0.91, "hip_spread": 0.045,
		"recoil_v": 0.032, "recoil_h": 0.013, "reload": 2.7, "ammo": "heavy",
		"mode": "semi", "pen": 1.3, "zoom": 6.0, "silent": false, "pitch": 0.68,
		"role": "Aluminum-chassis semi. Follow-up shots on demand.",
		"model": {"style": "semi", "barrel": 0.60, "mag": "curved", "stock": "chassis",
			"sight": "scope", "muzzle": "flash", "body": "graphite", "accent": "none", "extras": [], "receiver": "angular"}},
	{"id": "ol6", "name": "OL-6", "alias": "Sixgun", "cls": "sniper",
		"damage": 75, "rpm": 55, "range_near": 95.0, "range_far": 170.0,
		"mag": 6, "reserve0": 24, "ads": 0.33, "move": 0.93, "hip_spread": 0.05,
		"recoil_v": 0.036, "recoil_h": 0.015, "reload": 2.5, "ammo": "heavy",
		"mode": "bolt", "pen": 1.3, "zoom": 6.0, "silent": false, "pitch": 0.72,
		"sound": {"crack": 1.15}, "role": "Revolver-cylinder bolt-action. Fastest rechamber.",
		"model": {"style": "scout", "barrel": 0.50, "mag": "internal", "stock": "skeleton",
			"sight": "scope", "muzzle": "flash", "body": "bronze", "accent": "none", "extras": [], "cylinder": true}},
	{"id": "na45", "name": "NA-45", "alias": "Primer", "cls": "sniper",
		"damage": 75, "rpm": 60, "range_near": 60.0, "range_far": 120.0,
		"mag": 2, "reserve0": 10, "ads": 0.40, "move": 0.89, "hip_spread": 0.02,
		"recoil_v": 0.030, "recoil_h": 0.012, "reload": 3.0, "ammo": "heavy",
		"mode": "grenade", "pen": 1.0, "zoom": 6.0, "silent": false, "pitch": 0.66,
		"blast": 3.0, "proj_speed": 85.0, "proj_grav": 0.05,
		"role": "Explosive-trap sniper. Tag, then detonate.",
		"model": {"style": "semi", "barrel": 0.55, "mag": "straight", "stock": "skeleton",
			"sight": "scope", "muzzle": "none", "body": "graphite", "accent": "none", "extras": [], "receiver": "angular", "glow": "amber"}},
	{"id": "sv7", "name": "SV-7", "alias": "Sable", "cls": "sniper",
		"damage": 58, "rpm": 170, "range_near": 85.0, "range_far": 150.0,
		"mag": 10, "reserve0": 40, "ads": 0.34, "move": 0.93, "hip_spread": 0.04,
		"recoil_v": 0.030, "recoil_h": 0.012, "reload": 2.4, "ammo": "heavy",
		"mode": "semi", "pen": 1.2, "zoom": 6.0, "silent": false, "pitch": 0.75,
		"sound": {"body": 1.2}, "role": "Wooden thumbhole semi. Fast, mobile, hollow bark.",
		"model": {"style": "semi", "barrel": 0.62, "mag": "curved", "stock": "thumbhole",
			"sight": "scope", "muzzle": "flash", "body": "gunmetal", "accent": "wood", "extras": [], "toprail": false}},
	{"id": "ks12", "name": "KS-12", "alias": "Bantam", "cls": "sniper",
		"damage": 100, "rpm": 38, "range_near": 110.0, "range_far": 190.0,
		"mag": 5, "reserve0": 20, "ads": 0.40, "move": 0.90, "hip_spread": 0.055,
		"recoil_v": 0.050, "recoil_h": 0.020, "reload": 3.0, "ammo": "heavy",
		"mode": "bolt", "pen": 1.6, "zoom": 8.0, "silent": false, "pitch": 0.58,
		"sound": {"thump": 1.4}, "role": "Bullpup .50. Huge power, short package.",
		"model": {"style": "bullpup", "barrel": 0.62, "mag": "straight", "stock": "bullpup",
			"sight": "scopelong", "muzzle": "brake", "body": "black", "accent": "none", "extras": []}},
	{"id": "hd9", "name": "HD-9", "alias": "Summit", "cls": "sniper",
		"damage": 92, "rpm": 44, "range_near": 120.0, "range_far": 210.0,
		"mag": 5, "reserve0": 20, "ads": 0.42, "move": 0.89, "hip_spread": 0.05,
		"recoil_v": 0.045, "recoil_h": 0.017, "reload": 2.8, "ammo": "heavy",
		"mode": "bolt", "pen": 1.5, "zoom": 8.0, "silent": false, "pitch": 0.64,
		"role": "Modular bolt-action. Deep authoritative crack.",
		"model": {"style": "heavy", "barrel": 0.68, "mag": "straight", "stock": "folding",
			"sight": "scopelong", "muzzle": "brake", "body": "grey", "accent": "none", "extras": ["bipod"], "receiver": "angular"}},
	{"id": "lw3", "name": "LW-3", "alias": "Sportsman", "cls": "sniper",
		"damage": 85, "rpm": 48, "range_near": 100.0, "range_far": 180.0,
		"mag": 5, "reserve0": 20, "ads": 0.38, "move": 0.91, "hip_spread": 0.05,
		"recoil_v": 0.040, "recoil_h": 0.016, "reload": 2.6, "ammo": "heavy",
		"mode": "bolt", "pen": 1.3, "zoom": 6.0, "silent": false, "pitch": 0.68,
		"role": "Classic hunting bolt-action. Forgiving and accurate.",
		"model": {"style": "scout", "barrel": 0.60, "mag": "internal", "stock": "fixed",
			"sight": "scope", "muzzle": "none", "body": "bronze", "accent": "wood", "extras": [], "toprail": false}},
	{"id": "tl3", "name": "TL-3", "alias": "Antique", "cls": "sniper",
		"damage": 98, "rpm": 36, "range_near": 110.0, "range_far": 190.0,
		"mag": 5, "reserve0": 20, "ads": 0.44, "move": 0.89, "hip_spread": 0.055,
		"recoil_v": 0.052, "recoil_h": 0.020, "reload": 3.2, "ammo": "heavy",
		"mode": "bolt", "pen": 1.5, "zoom": 6.0, "silent": false, "pitch": 0.6,
		"sound": {"body": 1.2}, "role": "Vintage service rifle. Old-school bark, hard hits.",
		"model": {"style": "vintage", "barrel": 0.72, "mag": "internal", "stock": "fixed",
			"sight": "scope", "muzzle": "none", "body": "gunmetal", "accent": "wood", "extras": ["bayonet"], "toprail": false}},
	# ----------------- Pistols: expansion (CODM research) -----------------
	{"id": "j358", "name": "J-358", "alias": "Magnum", "cls": "pistol",
		"damage": 50, "rpm": 220, "range_near": 22.0, "range_far": 46.0,
		"mag": 6, "reserve0": 36, "ads": 0.22, "move": 1.0, "hip_spread": 0.014,
		"recoil_v": 0.028, "recoil_h": 0.015, "reload": 2.0, "ammo": "light",
		"mode": "semi", "pen": 0.9, "zoom": 0.0, "silent": false, "pitch": 0.72,
		"sound": {"thump": 1.3}, "role": "Magnum revolver. Slow, devastating, loud.",
		"model": {"style": "revolver", "barrel": 0.16, "mag": "none", "stock": "none",
			"sight": "iron", "muzzle": "none", "body": "gunmetal", "accent": "wood", "extras": []}},
	{"id": "rn9", "name": "RN-9", "alias": "Stutter", "cls": "pistol",
		"damage": 22, "rpm": 700, "range_near": 16.0, "range_far": 36.0,
		"mag": 15, "reserve0": 75, "ads": 0.18, "move": 1.03, "hip_spread": 0.013,
		"recoil_v": 0.011, "recoil_h": 0.010, "reload": 1.5, "ammo": "light",
		"mode": "burst", "pen": 0.6, "zoom": 0.0, "silent": false, "pitch": 1.2,
		"role": "Burst-fire pistol. Shreds up close.",
		"model": {"style": "burst", "barrel": 0.13, "mag": "stick", "stock": "none",
			"sight": "iron", "muzzle": "none", "body": "black", "accent": "none", "extras": []}},
	{"id": "sh2", "name": "SH-2", "alias": "Stub", "cls": "pistol",
		"damage": 60, "rpm": 120, "range_near": 8.0, "range_far": 16.0,
		"mag": 2, "reserve0": 16, "ads": 0.24, "move": 1.0, "hip_spread": 0.03,
		"recoil_v": 0.040, "recoil_h": 0.020, "reload": 2.2, "ammo": "light",
		"mode": "semi", "pen": 0.5, "zoom": 0.0, "silent": false, "pitch": 0.65,
		"sound": {"thump": 1.5}, "role": "Sawed-off shotgun pistol. Two-shot delete button.",
		"model": {"style": "shorty", "barrel": 0.10, "mag": "none", "stock": "none",
			"sight": "iron", "muzzle": "none", "body": "gunmetal", "accent": "wood", "extras": []}},
	{"id": "xb1", "name": "XB-1", "alias": "Arbalest", "cls": "pistol",
		"damage": 95, "rpm": 50, "range_near": 40.0, "range_far": 90.0,
		"mag": 1, "reserve0": 12, "ads": 0.26, "move": 1.0, "hip_spread": 0.01,
		"recoil_v": 0.020, "recoil_h": 0.008, "reload": 2.4, "ammo": "light",
		"mode": "grenade", "pen": 1.0, "zoom": 0.0, "silent": true, "pitch": 0.9,
		"blast": 1.2, "proj_speed": 55.0, "proj_grav": 0.35,
		"role": "Silent crossbow. One bolt, no flash, no sound.",
		"model": {"style": "crossbow", "barrel": 0.10, "mag": "none", "stock": "none",
			"sight": "reddot", "muzzle": "none", "body": "black", "accent": "none", "extras": []}},
	{"id": "lc9", "name": "LC-9", "alias": "Hummer", "cls": "pistol",
		"damage": 19, "rpm": 850, "range_near": 14.0, "range_far": 30.0,
		"mag": 24, "reserve0": 120, "ads": 0.18, "move": 1.03, "hip_spread": 0.014,
		"recoil_v": 0.010, "recoil_h": 0.011, "reload": 1.6, "ammo": "light",
		"mode": "auto", "pen": 0.5, "zoom": 0.0, "silent": false, "pitch": 1.3,
		"sound": {"crack": 1.2, "dur": 0.85}, "role": "Full-auto pocket SMG. Best CQB secondary.",
		"model": {"style": "fullauto", "barrel": 0.12, "mag": "stick", "stock": "none",
			"sight": "iron", "muzzle": "comp", "body": "grey", "accent": "none", "extras": []}},
	{"id": "ng9", "name": "NG-9", "alias": "Carpenter", "cls": "pistol",
		"damage": 14, "rpm": 700, "range_near": 12.0, "range_far": 26.0,
		"mag": 30, "reserve0": 150, "ads": 0.18, "move": 1.03, "hip_spread": 0.015,
		"recoil_v": 0.009, "recoil_h": 0.010, "reload": 1.8, "ammo": "light",
		"mode": "auto", "pen": 0.4, "zoom": 0.0, "silent": false, "pitch": 1.25,
		"sound": {"crack": 1.5, "thump": 0.3, "body": 1.6}, "role": "Pneumatic nail gun. Phut-phut-phut DPS.",
		"model": {"style": "nailgun", "barrel": 0.10, "mag": "none", "stock": "none",
			"sight": "iron", "muzzle": "none", "body": "graphite", "accent": "none", "extras": []}},
	# ---------------- Launchers: expansion (CODM research) ----------------
	{"id": "fj18", "name": "FJ-18", "alias": "Skysweeper", "cls": "launcher",
		"damage": 110, "rpm": 35, "range_near": 80.0, "range_far": 160.0,
		"mag": 1, "reserve0": 3, "ads": 0.42, "move": 0.87, "hip_spread": 0.015,
		"recoil_v": 0.040, "recoil_h": 0.010, "reload": 3.0, "ammo": "rocket",
		"mode": "rocket", "pen": 0.0, "zoom": 0.0, "silent": false, "pitch": 0.55,
		"blast": 5.0, "proj_speed": 60.0, "proj_grav": 0.02,
		"role": "Lock-on AA launcher. Melts anything airborne.",
		"model": {"style": "stinger", "barrel": 0.0, "mag": "none", "stock": "none",
			"sight": "iron", "muzzle": "none", "body": "od", "accent": "none", "extras": []}},
	{"id": "d13", "name": "D-13", "alias": "Ricochet", "cls": "launcher",
		"damage": 85, "rpm": 55, "range_near": 40.0, "range_far": 90.0,
		"mag": 3, "reserve0": 6, "ads": 0.36, "move": 0.90, "hip_spread": 0.02,
		"recoil_v": 0.030, "recoil_h": 0.010, "reload": 2.8, "ammo": "grenade",
		"mode": "grenade", "pen": 0.0, "zoom": 0.0, "silent": false, "pitch": 0.7,
		"sound": {"crack": 1.3}, "blast": 4.0, "proj_speed": 30.0, "proj_grav": 0.6,
		"role": "Disc launcher. Bank trick shots off walls.",
		"model": {"style": "disc", "barrel": 0.0, "mag": "none", "stock": "none",
			"sight": "reddot", "muzzle": "none", "body": "graphite", "accent": "none", "extras": [], "glow": "cyan"}},
	{"id": "rp7", "name": "RP-7", "alias": "Thunderhead", "cls": "launcher",
		"damage": 150, "rpm": 30, "range_near": 60.0, "range_far": 140.0,
		"mag": 1, "reserve0": 2, "ads": 0.44, "move": 0.86, "hip_spread": 0.022,
		"recoil_v": 0.050, "recoil_h": 0.012, "reload": 3.4, "ammo": "rocket",
		"mode": "rocket", "pen": 0.0, "zoom": 0.0, "silent": false, "pitch": 0.5,
		"sound": {"whoosh": 1.0, "dur": 1.2}, "blast": 5.5, "proj_speed": 55.0, "proj_grav": 0.06,
		"role": "Classic RPG. Front-loaded warhead, huge blast.",
		"model": {"style": "rpg7", "barrel": 0.0, "mag": "none", "stock": "none",
			"sight": "iron", "muzzle": "none", "body": "od", "accent": "wood", "extras": []}},
	# ------------------ Melee: expansion (CODM research) ------------------
	{"id": "bat", "name": "BAT", "alias": "Slugger", "cls": "melee",
		"damage": 65, "rpm": 85, "range_near": 2.5, "range_far": 2.5,
		"mag": 1, "reserve0": 0, "ads": 0.13, "move": 1.05, "hip_spread": 0.0,
		"recoil_v": 0.0, "recoil_h": 0.0, "reload": 0.55, "ammo": "none",
		"mode": "melee", "pen": 0.0, "zoom": 0.0, "silent": true, "pitch": 1.0,
		"role": "Baseball bat. Satisfying crack on hit.",
		"model": {"style": "bat", "barrel": 0.0, "mag": "none", "stock": "none",
			"sight": "none", "muzzle": "none", "body": "black", "accent": "wood", "extras": []}},
	{"id": "shovel", "name": "SHOVEL", "alias": "Digger", "cls": "melee",
		"damage": 75, "rpm": 70, "range_near": 2.4, "range_far": 2.4,
		"mag": 1, "reserve0": 0, "ads": 0.14, "move": 1.04, "hip_spread": 0.0,
		"recoil_v": 0.0, "recoil_h": 0.0, "reload": 0.6, "ammo": "none",
		"mode": "melee", "pen": 0.0, "zoom": 0.0, "silent": true, "pitch": 0.9,
		"role": "Entrenching tool. Heavy overhead chop.",
		"model": {"style": "shovel", "barrel": 0.0, "mag": "none", "stock": "none",
			"sight": "none", "muzzle": "none", "body": "black", "accent": "wood", "extras": []}},
	{"id": "machete", "name": "MACHETE", "alias": "Bushwhacker", "cls": "melee",
		"damage": 70, "rpm": 80, "range_near": 2.6, "range_far": 2.6,
		"mag": 1, "reserve0": 0, "ads": 0.13, "move": 1.05, "hip_spread": 0.0,
		"recoil_v": 0.0, "recoil_h": 0.0, "reload": 0.55, "ammo": "none",
		"mode": "melee", "pen": 0.0, "zoom": 0.0, "silent": true, "pitch": 1.0,
		"role": "Broad heavy blade. Wide slashing arcs.",
		"model": {"style": "machete", "barrel": 0.0, "mag": "none", "stock": "none",
			"sight": "none", "muzzle": "none", "body": "black", "accent": "none", "extras": []}},
	{"id": "fists", "name": "FISTS", "alias": "Brawler", "cls": "melee",
		"damage": 50, "rpm": 120, "range_near": 2.0, "range_far": 2.0,
		"mag": 1, "reserve0": 0, "ads": 0.12, "move": 1.06, "hip_spread": 0.0,
		"recoil_v": 0.0, "recoil_h": 0.0, "reload": 0.5, "ammo": "none",
		"mode": "melee", "pen": 0.0, "zoom": 0.0, "silent": true, "pitch": 1.1,
		"role": "Weighted gauntlets. Rapid punching combos.",
		"model": {"style": "fists", "barrel": 0.0, "mag": "none", "stock": "none",
			"sight": "none", "muzzle": "none", "body": "black", "accent": "none", "extras": []}},
	{"id": "sticks", "name": "STICKS", "alias": "Escrima", "cls": "melee",
		"damage": 55, "rpm": 110, "range_near": 2.5, "range_far": 2.5,
		"mag": 1, "reserve0": 0, "ads": 0.12, "move": 1.06, "hip_spread": 0.0,
		"recoil_v": 0.0, "recoil_h": 0.0, "reload": 0.5, "ammo": "none",
		"mode": "melee", "pen": 0.0, "zoom": 0.0, "silent": true, "pitch": 1.05,
		"role": "Twin rattan batons. Rapid alternating strikes.",
		"model": {"style": "sticks", "barrel": 0.0, "mag": "none", "stock": "none",
			"sight": "none", "muzzle": "none", "body": "black", "accent": "wood", "extras": []}},
	{"id": "sai", "name": "SAI", "alias": "Trapper", "cls": "melee",
		"damage": 60, "rpm": 100, "range_near": 2.2, "range_far": 2.2,
		"mag": 1, "reserve0": 0, "ads": 0.12, "move": 1.06, "hip_spread": 0.0,
		"recoil_v": 0.0, "recoil_h": 0.0, "reload": 0.5, "ammo": "none",
		"mode": "melee", "pen": 0.0, "zoom": 0.0, "silent": true, "pitch": 1.05,
		"role": "Twin pronged daggers. Fast thrusts and traps.",
		"model": {"style": "sai", "barrel": 0.0, "mag": "none", "stock": "none",
			"sight": "none", "muzzle": "none", "body": "black", "accent": "none", "extras": []}},
	{"id": "wrench", "name": "WRENCH", "alias": "Pipefitter", "cls": "melee",
		"damage": 72, "rpm": 75, "range_near": 2.3, "range_far": 2.3,
		"mag": 1, "reserve0": 0, "ads": 0.13, "move": 1.05, "hip_spread": 0.0,
		"recoil_v": 0.0, "recoil_h": 0.0, "reload": 0.55, "ammo": "none",
		"mode": "melee", "pen": 0.0, "zoom": 0.0, "silent": true, "pitch": 0.95,
		"role": "Heavy wrench. Industrial-strength persuasion.",
		"model": {"style": "wrench", "barrel": 0.0, "mag": "none", "stock": "none",
			"sight": "none", "muzzle": "none", "body": "black", "accent": "none", "extras": []}},
	# ------------------- SMGs: expansion (CODM research) -------------------
	{"id": "ru79", "name": "RU-79", "alias": "Barker", "cls": "smg",
		"damage": 30, "rpm": 700, "range_near": 16.0, "range_far": 34.0,
		"mag": 30, "reserve0": 150, "ads": 0.21, "move": 0.99, "hip_spread": 0.016,
		"recoil_v": 0.014, "recoil_h": 0.012, "reload": 2.0, "ammo": "light",
		"mode": "auto", "pen": 0.75, "zoom": 0.0, "silent": false, "pitch": 0.95,
		"sound": {"thump": 1.3}, "role": "Short AK carbine. Hard-hitting hybrid bark.",
		"model": {"style": "compact", "barrel": 0.24, "mag": "curved", "stock": "folding",
			"sight": "iron", "muzzle": "comp", "body": "gunmetal", "accent": "wood", "extras": []}},
	{"id": "pd57", "name": "PD-57", "alias": "Flatline", "cls": "smg",
		"damage": 22, "rpm": 850, "range_near": 14.0, "range_far": 30.0,
		"mag": 50, "reserve0": 150, "ads": 0.20, "move": 1.0, "hip_spread": 0.016,
		"recoil_v": 0.012, "recoil_h": 0.012, "reload": 2.2, "ammo": "light",
		"mode": "auto", "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.15,
		"sound": {"crack": 1.2}, "role": "Bullpup with 50-rd top mag. Sci-fi bullet hose.",
		"model": {"style": "bullpup", "barrel": 0.22, "mag": "helix", "stock": "bullpup",
			"sight": "iron", "muzzle": "flash", "body": "grey", "accent": "none", "extras": []}},
	{"id": "hg40", "name": "HG-40", "alias": "Vintage", "cls": "smg",
		"damage": 28, "rpm": 500, "range_near": 17.0, "range_far": 36.0,
		"mag": 32, "reserve0": 160, "ads": 0.22, "move": 0.99, "hip_spread": 0.014,
		"recoil_v": 0.013, "recoil_h": 0.010, "reload": 2.1, "ammo": "light",
		"mode": "auto", "pen": 0.75, "zoom": 0.0, "silent": false, "pitch": 0.85,
		"sound": {"body": 1.2}, "role": "WWII stamped steel. Slow, accurate, metallic.",
		"model": {"style": "surplus", "barrel": 0.26, "mag": "straight", "stock": "folding",
			"sight": "iron", "muzzle": "none", "body": "gunmetal", "accent": "none", "extras": [], "toprail": false, "receiver": "tube"}},
	{"id": "cc9", "name": "CC-9", "alias": "Staccato", "cls": "smg",
		"damage": 26, "rpm": 650, "range_near": 15.0, "range_far": 32.0,
		"mag": 24, "reserve0": 120, "ads": 0.20, "move": 1.0, "hip_spread": 0.015,
		"recoil_v": 0.013, "recoil_h": 0.011, "reload": 1.9, "ammo": "light",
		"mode": "burst", "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.1,
		"role": "Compact burst SMG. Vented shroud, sharp triple-tap.",
		"model": {"style": "compact", "barrel": 0.24, "mag": "curved", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "black", "accent": "none", "extras": ["heatshield"]}},
	{"id": "ms9", "name": "MS-9", "alias": "Angular", "cls": "smg",
		"damage": 25, "rpm": 750, "range_near": 15.0, "range_far": 33.0,
		"mag": 32, "reserve0": 160, "ads": 0.20, "move": 1.0, "hip_spread": 0.015,
		"recoil_v": 0.012, "recoil_h": 0.012, "reload": 1.8, "ammo": "light",
		"mode": "auto", "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.08,
		"role": "Angular polymer all-rounder. Balanced and snappy.",
		"model": {"style": "modular", "barrel": 0.22, "mag": "curved", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "graphite", "accent": "none", "extras": [], "receiver": "angular"}},
	{"id": "rz9", "name": "RZ-9", "alias": "Laser", "cls": "smg",
		"damage": 23, "rpm": 750, "range_near": 18.0, "range_far": 38.0,
		"mag": 32, "reserve0": 160, "ads": 0.20, "move": 1.0, "hip_spread": 0.012,
		"recoil_v": 0.010, "recoil_h": 0.009, "reload": 1.9, "ammo": "light",
		"mode": "auto", "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.05,
		"sound": {"crack": 0.9}, "role": "Sleek future SMG. Laser-accurate at mid range.",
		"model": {"style": "stealth", "barrel": 0.26, "mag": "straight", "stock": "folding",
			"sight": "iron", "muzzle": "shroud", "body": "black", "accent": "none", "extras": [], "receiver": "slim"}},
	{"id": "ph9", "name": "PH-9", "alias": "Quad", "cls": "smg",
		"damage": 24, "rpm": 700, "range_near": 14.0, "range_far": 30.0,
		"mag": 32, "reserve0": 160, "ads": 0.20, "move": 1.0, "hip_spread": 0.016,
		"recoil_v": 0.013, "recoil_h": 0.012, "reload": 1.9, "ammo": "light",
		"mode": "burst", "burst_n": 4, "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.12,
		"role": "4-round burst shredder. Boxy and brutal up close.",
		"model": {"style": "compact", "barrel": 0.20, "mag": "straight", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "grey", "accent": "none", "extras": [], "receiver": "boxy"}},
	{"id": "gk9", "name": "GK-9", "alias": "Clean", "cls": "smg",
		"damage": 25, "rpm": 750, "range_near": 16.0, "range_far": 34.0,
		"mag": 32, "reserve0": 160, "ads": 0.19, "move": 1.0, "hip_spread": 0.014,
		"recoil_v": 0.012, "recoil_h": 0.011, "reload": 1.8, "ammo": "light",
		"mode": "auto", "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.06,
		"role": "Minimalist modern SMG. Steady and versatile.",
		"model": {"style": "modular", "barrel": 0.24, "mag": "straight", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "black", "accent": "none", "extras": [], "receiver": "slim"}},
	{"id": "cd70", "name": "CD-70", "alias": "Coffin", "cls": "smg",
		"damage": 23, "rpm": 700, "range_near": 15.0, "range_far": 32.0,
		"mag": 70, "reserve0": 140, "ads": 0.24, "move": 0.98, "hip_spread": 0.017,
		"recoil_v": 0.013, "recoil_h": 0.013, "reload": 2.6, "ammo": "light",
		"mode": "auto", "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.0,
		"sound": {"crack": 1.1}, "role": "70-round coffin mag. Dump for days.",
		"model": {"style": "box", "barrel": 0.24, "mag": "casket", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "gunmetal", "accent": "none", "extras": [], "receiver": "boxy"}},
	{"id": "qq9", "name": "QQ-9", "alias": "Classic", "cls": "smg",
		"damage": 26, "rpm": 800, "range_near": 16.0, "range_far": 34.0,
		"mag": 30, "reserve0": 150, "ads": 0.20, "move": 1.0, "hip_spread": 0.014,
		"recoil_v": 0.012, "recoil_h": 0.011, "reload": 1.8, "ammo": "light",
		"mode": "auto", "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.05,
		"sound": {"thump": 1.1}, "role": "The classic SMG silhouette. Smooth and controllable.",
		"model": {"style": "classic", "barrel": 0.22, "mag": "curved", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "black", "accent": "none", "extras": []}},
	{"id": "fn9", "name": "FN-9", "alias": "Buzzkill", "cls": "smg",
		"damage": 21, "rpm": 1100, "range_near": 13.0, "range_far": 28.0,
		"mag": 32, "reserve0": 160, "ads": 0.19, "move": 1.01, "hip_spread": 0.017,
		"recoil_v": 0.012, "recoil_h": 0.014, "reload": 1.8, "ammo": "light",
		"mode": "auto", "pen": 0.6, "zoom": 0.0, "silent": false, "pitch": 1.22,
		"sound": {"crack": 1.3, "dur": 0.8}, "role": "Offset-receiver buzzsaw. Fastest in class.",
		"model": {"style": "rapid", "barrel": 0.16, "mag": "straight", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "graphite", "accent": "none", "extras": [], "receiver": "angular"}},
	{"id": "ag55", "name": "AG-55", "alias": "Waffle", "cls": "smg",
		"damage": 24, "rpm": 700, "range_near": 17.0, "range_far": 36.0,
		"mag": 30, "reserve0": 150, "ads": 0.21, "move": 0.99, "hip_spread": 0.014,
		"recoil_v": 0.012, "recoil_h": 0.010, "reload": 1.9, "ammo": "light",
		"mode": "auto", "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.04,
		"sound": {"body": 1.1}, "role": "Bullpup with waffle mag. Accurate and hollow-popping.",
		"model": {"style": "bullpup", "barrel": 0.24, "mag": "casket", "stock": "bullpup",
			"sight": "iron", "muzzle": "flash", "body": "od", "accent": "none", "extras": ["foregrip"], "carry_handle": true}},
	{"id": "qx9", "name": "QX-9", "alias": "Sting", "cls": "smg",
		"damage": 22, "rpm": 950, "range_near": 14.0, "range_far": 30.0,
		"mag": 40, "reserve0": 160, "ads": 0.18, "move": 1.01, "hip_spread": 0.015,
		"recoil_v": 0.011, "recoil_h": 0.012, "reload": 1.9, "ammo": "light",
		"mode": "auto", "pen": 0.65, "zoom": 0.0, "silent": false, "pitch": 1.2,
		"sound": {"crack": 1.25}, "role": "Pocket rocket. Needle crack, fastest handling.",
		"model": {"style": "compact", "barrel": 0.18, "mag": "stick", "stock": "wire",
			"sight": "iron", "muzzle": "shroud", "body": "black", "accent": "none", "extras": ["foregrip"]}},
	{"id": "bz64", "name": "BZ-64", "alias": "Helix", "cls": "smg",
		"damage": 23, "rpm": 700, "range_near": 15.0, "range_far": 32.0,
		"mag": 64, "reserve0": 128, "ads": 0.23, "move": 0.98, "hip_spread": 0.016,
		"recoil_v": 0.013, "recoil_h": 0.012, "reload": 2.6, "ammo": "light",
		"mode": "auto", "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.0,
		"role": "64-round helical tube under the barrel. Sustain king.",
		"model": {"style": "piston", "barrel": 0.28, "mag": "helixunder", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "gunmetal", "accent": "none", "extras": []}},
	{"id": "mx9", "name": "MX-9", "alias": "Para", "cls": "smg",
		"damage": 24, "rpm": 800, "range_near": 14.0, "range_far": 30.0,
		"mag": 30, "reserve0": 150, "ads": 0.19, "move": 1.01, "hip_spread": 0.015,
		"recoil_v": 0.012, "recoil_h": 0.012, "reload": 1.8, "ammo": "light",
		"mode": "auto", "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.12,
		"role": "Stubby bullpup hose. Mag-in-grip compactness.",
		"model": {"style": "bullpup", "barrel": 0.18, "mag": "stick", "stock": "bullpup",
			"sight": "iron", "muzzle": "flash", "body": "black", "accent": "none", "extras": ["foregrip"]}},
	{"id": "cb4", "name": "CB-4", "alias": "Topfeed", "cls": "smg",
		"damage": 23, "rpm": 900, "range_near": 15.0, "range_far": 32.0,
		"mag": 50, "reserve0": 150, "ads": 0.20, "move": 1.0, "hip_spread": 0.015,
		"recoil_v": 0.012, "recoil_h": 0.012, "reload": 2.2, "ammo": "light",
		"mode": "auto", "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.15,
		"sound": {"crack": 1.15}, "role": "Top-mounted 50-rd mag. Whirring laser.",
		"model": {"style": "compact", "barrel": 0.22, "mag": "helix", "stock": "fixed",
			"sight": "reddot", "muzzle": "flash", "body": "tan", "accent": "none", "extras": [], "receiver": "angular"}},
	{"id": "pp41", "name": "PP-41", "alias": "Brrrt", "cls": "smg",
		"damage": 24, "rpm": 900, "range_near": 14.0, "range_far": 30.0,
		"mag": 71, "reserve0": 142, "ads": 0.23, "move": 0.98, "hip_spread": 0.017,
		"recoil_v": 0.014, "recoil_h": 0.013, "reload": 2.8, "ammo": "light",
		"mode": "auto", "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.05,
		"sound": {"thump": 1.2}, "role": "WWII drum-fed hose. Iconic brrrrt.",
		"model": {"style": "surplus", "barrel": 0.28, "mag": "drum", "stock": "fixed",
			"sight": "iron", "muzzle": "none", "body": "gunmetal", "accent": "wood", "extras": ["heatshield"], "toprail": false}},
	{"id": "mc10", "name": "MC-10", "alias": "Pocket", "cls": "smg",
		"damage": 20, "rpm": 1150, "range_near": 12.0, "range_far": 26.0,
		"mag": 32, "reserve0": 160, "ads": 0.17, "move": 1.02, "hip_spread": 0.018,
		"recoil_v": 0.011, "recoil_h": 0.014, "reload": 1.7, "ammo": "light",
		"mode": "auto", "pen": 0.6, "zoom": 0.0, "silent": false, "pitch": 1.25,
		"sound": {"crack": 1.3, "dur": 0.75}, "role": "Tiny box shredder. Angry pocket buzz.",
		"model": {"style": "machine", "barrel": 0.14, "mag": "stick", "stock": "wire",
			"sight": "none", "muzzle": "flash", "body": "grey", "accent": "none", "extras": [], "receiver": "boxy"}},
	{"id": "ks45", "name": "KS-45", "alias": "Heavyburst", "cls": "smg",
		"damage": 30, "rpm": 600, "range_near": 15.0, "range_far": 32.0,
		"mag": 24, "reserve0": 120, "ads": 0.21, "move": 0.99, "hip_spread": 0.015,
		"recoil_v": 0.014, "recoil_h": 0.011, "reload": 2.0, "ammo": "light",
		"mode": "burst", "pen": 0.8, "zoom": 0.0, "silent": false, "pitch": 0.9,
		"sound": {"thump": 1.3}, "role": "Heavy .45 burst. Slow, deliberate thump.",
		"model": {"style": "heavy", "barrel": 0.24, "mag": "straight", "stock": "folding",
			"sight": "iron", "muzzle": "comp", "body": "black", "accent": "none", "extras": []}},
	{"id": "sw9", "name": "SW-9", "alias": "Switch", "cls": "smg",
		"damage": 25, "rpm": 850, "range_near": 15.0, "range_far": 32.0,
		"mag": 32, "reserve0": 160, "ads": 0.19, "move": 1.01, "hip_spread": 0.015,
		"recoil_v": 0.012, "recoil_h": 0.012, "reload": 1.8, "ammo": "light",
		"mode": "auto", "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.14,
		"role": "Aggressive run-and-gun. Skeleton stock, angled body.",
		"model": {"style": "tactical", "barrel": 0.20, "mag": "straight", "stock": "skeleton",
			"sight": "iron", "muzzle": "flash", "body": "graphite", "accent": "none", "extras": [], "receiver": "angular"}},
	{"id": "lp9", "name": "LP-9", "alias": "Quirk", "cls": "smg",
		"damage": 26, "rpm": 700, "range_near": 15.0, "range_far": 32.0,
		"mag": 30, "reserve0": 150, "ads": 0.20, "move": 1.0, "hip_spread": 0.015,
		"recoil_v": 0.013, "recoil_h": 0.011, "reload": 1.9, "ammo": "light",
		"mode": "auto", "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.06,
		"role": "Quirky bullpup prototype. Boxy and mid-pitched.",
		"model": {"style": "bullpup", "barrel": 0.22, "mag": "straight", "stock": "bullpup",
			"sight": "iron", "muzzle": "flash", "body": "bluegrey", "accent": "none", "extras": ["foregrip"], "receiver": "boxy"}},
	{"id": "ot9", "name": "OT-9", "alias": "Tiny", "cls": "smg",
		"damage": 23, "rpm": 900, "range_near": 13.0, "range_far": 28.0,
		"mag": 20, "reserve0": 120, "ads": 0.18, "move": 1.02, "hip_spread": 0.016,
		"recoil_v": 0.011, "recoil_h": 0.013, "reload": 1.7, "ammo": "light",
		"mode": "auto", "pen": 0.65, "zoom": 0.0, "silent": false, "pitch": 1.2,
		"sound": {"crack": 1.2}, "role": "Tiny Russian speedster. Top-folding wire stock.",
		"model": {"style": "compact", "barrel": 0.14, "mag": "stick", "stock": "wire",
			"sight": "iron", "muzzle": "flash", "body": "black", "accent": "none", "extras": []}},
	{"id": "st45", "name": "ST-45", "alias": "Ram", "cls": "smg",
		"damage": 32, "rpm": 600, "range_near": 15.0, "range_far": 32.0,
		"mag": 25, "reserve0": 125, "ads": 0.21, "move": 0.99, "hip_spread": 0.015,
		"recoil_v": 0.014, "recoil_h": 0.011, "reload": 2.0, "ammo": "light",
		"mode": "auto", "pen": 0.8, "zoom": 0.0, "silent": false, "pitch": 0.88,
		"sound": {"thump": 1.3}, "role": "Heavy .45 SMG. Deliberate, punishing thump.",
		"model": {"style": "heavy", "barrel": 0.26, "mag": "straight", "stock": "folding",
			"sight": "iron", "muzzle": "comp", "body": "od", "accent": "none", "extras": []}},
	{"id": "cx9", "name": "CX-9", "alias": "Scorpion", "cls": "smg",
		"damage": 24, "rpm": 850, "range_near": 15.0, "range_far": 33.0,
		"mag": 32, "reserve0": 160, "ads": 0.19, "move": 1.01, "hip_spread": 0.014,
		"recoil_v": 0.012, "recoil_h": 0.012, "reload": 1.8, "ammo": "light",
		"mode": "auto", "pen": 0.7, "zoom": 0.0, "silent": false, "pitch": 1.14,
		"role": "Modern fast SMG. Crisp and aggressive.",
		"model": {"style": "rapid", "barrel": 0.20, "mag": "curved", "stock": "folding",
			"sight": "iron", "muzzle": "flash", "body": "black", "accent": "none", "extras": [], "receiver": "slim"}},
	{"id": "tc9", "name": "TC-9", "alias": "Clanky", "cls": "smg",
		"damage": 22, "rpm": 750, "range_near": 14.0, "range_far": 30.0,
		"mag": 32, "reserve0": 160, "ads": 0.20, "move": 1.0, "hip_spread": 0.016,
		"recoil_v": 0.012, "recoil_h": 0.013, "reload": 1.9, "ammo": "light",
		"mode": "auto", "pen": 0.65, "zoom": 0.0, "silent": false, "pitch": 1.1,
		"sound": {"body": 1.3}, "role": "Open-bolt machine pistol. Clanky slap-crack.",
		"model": {"style": "machine", "barrel": 0.22, "mag": "stick", "stock": "wire",
			"sight": "iron", "muzzle": "flash", "body": "gunmetal", "accent": "none", "extras": [], "receiver": "tube"}},
	# ----------------- Shotguns: expansion (CODM research) -----------------
	{"id": "by15", "name": "BY-15", "alias": "Classic", "cls": "shotgun",
		"damage": 9, "pellets": 8, "rpm": 70, "range_near": 10.0, "range_far": 22.0,
		"mag": 6, "reserve0": 24, "ads": 0.30, "move": 0.95, "hip_spread": 0.05,
		"recoil_v": 0.045, "recoil_h": 0.020, "reload": 2.6, "ammo": "shell",
		"mode": "pump", "pen": 0.5, "zoom": 0.0, "silent": false, "pitch": 0.72,
		"role": "The classic pump. One pump, one kill.",
		"model": {"style": "pump", "barrel": 0.50, "mag": "tube", "stock": "fixed",
			"sight": "iron", "muzzle": "none", "body": "black", "accent": "wood", "extras": [], "toprail": false}},
	{"id": "sk12", "name": "SK-12", "alias": "Revolver", "cls": "shotgun",
		"damage": 8, "pellets": 8, "rpm": 180, "range_near": 10.0, "range_far": 22.0,
		"mag": 12, "reserve0": 36, "ads": 0.28, "move": 0.94, "hip_spread": 0.05,
		"recoil_v": 0.038, "recoil_h": 0.018, "reload": 3.2, "ammo": "shell",
		"mode": "semi", "pen": 0.5, "zoom": 0.0, "silent": false, "pitch": 0.78,
		"role": "12-shell revolving cylinder. Drum-fed rhythm.",
		"model": {"style": "rapid", "barrel": 0.36, "mag": "drum", "stock": "folding",
			"sight": "iron", "muzzle": "none", "body": "gunmetal", "accent": "none", "extras": []}},
	{"id": "hs21", "name": "HS-21", "alias": "Blocky", "cls": "shotgun",
		"damage": 7, "pellets": 6, "rpm": 300, "range_near": 10.0, "range_far": 22.0,
		"mag": 16, "reserve0": 32, "ads": 0.28, "move": 0.94, "hip_spread": 0.05,
		"recoil_v": 0.035, "recoil_h": 0.018, "reload": 2.6, "ammo": "shell",
		"mode": "burst", "burst_n": 4, "pen": 0.5, "zoom": 0.0, "silent": false, "pitch": 0.85,
		"role": "4-shell burst. Doesn't look like a shotgun, clears rooms.",
		"model": {"style": "auto", "barrel": 0.34, "mag": "box", "stock": "fixed",
			"sight": "reddot", "muzzle": "none", "body": "graphite", "accent": "none", "extras": [], "receiver": "boxy"}},
	{"id": "hs04", "name": "HS-04", "alias": "Lever", "cls": "shotgun",
		"damage": 10, "pellets": 8, "rpm": 65, "range_near": 11.0, "range_far": 24.0,
		"mag": 5, "reserve0": 20, "ads": 0.30, "move": 0.94, "hip_spread": 0.05,
		"recoil_v": 0.048, "recoil_h": 0.020, "reload": 2.6, "ammo": "shell",
		"mode": "pump", "pen": 0.5, "zoom": 0.0, "silent": false, "pitch": 0.68,
		"sound": {"body": 1.2}, "role": "Lever-action shotgun. Boom plus lever-clack.",
		"model": {"style": "pump", "barrel": 0.52, "mag": "tube", "stock": "fixed",
			"sight": "iron", "muzzle": "none", "body": "gunmetal", "accent": "wood", "extras": [], "lever": true, "toprail": false}},
	{"id": "km26", "name": "KM-26", "alias": "Versatile", "cls": "shotgun",
		"damage": 9, "pellets": 8, "rpm": 72, "range_near": 10.0, "range_far": 22.0,
		"mag": 6, "reserve0": 24, "ads": 0.29, "move": 0.95, "hip_spread": 0.05,
		"recoil_v": 0.044, "recoil_h": 0.019, "reload": 2.5, "ammo": "shell",
		"mode": "pump", "pen": 0.5, "zoom": 0.0, "silent": false, "pitch": 0.74,
		"role": "Balanced pump. The dependable middle ground.",
		"model": {"style": "pump", "barrel": 0.46, "mag": "tube", "stock": "fixed",
			"sight": "iron", "muzzle": "none", "body": "od", "accent": "none", "extras": []}},
	{"id": "ec12", "name": "EC-12", "alias": "Boxfed", "cls": "shotgun",
		"damage": 8, "pellets": 8, "rpm": 200, "range_near": 10.0, "range_far": 22.0,
		"mag": 12, "reserve0": 36, "ads": 0.28, "move": 0.95, "hip_spread": 0.05,
		"recoil_v": 0.038, "recoil_h": 0.018, "reload": 2.4, "ammo": "shell",
		"mode": "semi", "pen": 0.5, "zoom": 0.0, "silent": false, "pitch": 0.78,
		"role": "Box-mag semi-auto. AR ergonomics, shotgun soul.",
		"model": {"style": "semi", "barrel": 0.38, "mag": "box", "stock": "folding",
			"sight": "iron", "muzzle": "none", "body": "black", "accent": "none", "extras": []}},
	{"id": "r90", "name": "R9-0", "alias": "Twobarrel", "cls": "shotgun",
		"damage": 9, "pellets": 10, "rpm": 60, "range_near": 9.0, "range_far": 20.0,
		"mag": 8, "reserve0": 32, "ads": 0.30, "move": 0.94, "hip_spread": 0.055,
		"recoil_v": 0.050, "recoil_h": 0.022, "reload": 2.8, "ammo": "shell",
		"mode": "pump", "pen": 0.5, "zoom": 0.0, "silent": false, "pitch": 0.66,
		"sound": {"thump": 1.3}, "role": "Double-barrel pump. Boom-boom per cycle.",
		"model": {"style": "pump", "barrel": 0.44, "mag": "saddle", "stock": "fixed",
			"sight": "iron", "muzzle": "none", "body": "black", "accent": "none", "extras": [], "twinbarrel": true}},
	# ---------------- Marksman: expansion (CODM research) ----------------
	{"id": "kb98", "name": "KB-98", "alias": "Kar", "cls": "marksman",
		"damage": 70, "rpm": 55, "range_near": 70.0, "range_far": 130.0,
		"mag": 5, "reserve0": 25, "ads": 0.36, "move": 0.91, "hip_spread": 0.022,
		"recoil_v": 0.034, "recoil_h": 0.014, "reload": 2.6, "ammo": "medium",
		"mode": "bolt", "pen": 1.3, "zoom": 4.0, "silent": false, "pitch": 0.72,
		"sound": {"body": 1.2}, "role": "Bolt-action marksman. One precise shot.",
		"model": {"style": "vintage", "barrel": 0.60, "mag": "internal", "stock": "fixed",
			"sight": "scope", "muzzle": "none", "body": "gunmetal", "accent": "wood", "extras": [], "toprail": false}},
	{"id": "sk45", "name": "SK-45", "alias": "Carbine", "cls": "marksman",
		"damage": 52, "rpm": 200, "range_near": 58.0, "range_far": 105.0,
		"mag": 10, "reserve0": 50, "ads": 0.30, "move": 0.93, "hip_spread": 0.019,
		"recoil_v": 0.026, "recoil_h": 0.011, "reload": 2.2, "ammo": "medium",
		"mode": "semi", "pen": 1.2, "zoom": 4.0, "silent": false, "pitch": 0.8,
		"role": "Classic semi-auto carbine. Steady tap-tap.",
		"model": {"style": "carbine", "barrel": 0.52, "mag": "internal", "stock": "fixed",
			"sight": "scope", "muzzle": "none", "body": "gunmetal", "accent": "wood", "extras": ["bayonet"], "toprail": false}},
	{"id": "sp20", "name": "SP-20", "alias": "Hunter", "cls": "marksman",
		"damage": 68, "rpm": 60, "range_near": 65.0, "range_far": 125.0,
		"mag": 5, "reserve0": 25, "ads": 0.34, "move": 0.92, "hip_spread": 0.020,
		"recoil_v": 0.032, "recoil_h": 0.013, "reload": 2.4, "ammo": "medium",
		"mode": "bolt", "pen": 1.3, "zoom": 4.0, "silent": false, "pitch": 0.74,
		"role": "Precision hunting bolt-action. Deep and deliberate.",
		"model": {"style": "scout", "barrel": 0.58, "mag": "internal", "stock": "fixed",
			"sight": "scope", "muzzle": "none", "body": "bronze", "accent": "wood", "extras": [], "toprail": false}},
	{"id": "m1g", "name": "M1-G", "alias": "Ping", "cls": "marksman",
		"damage": 60, "rpm": 190, "range_near": 62.0, "range_far": 115.0,
		"mag": 8, "reserve0": 40, "ads": 0.32, "move": 0.92, "hip_spread": 0.020,
		"recoil_v": 0.030, "recoil_h": 0.012, "reload": 2.8, "ammo": "medium",
		"mode": "semi", "pen": 1.3, "zoom": 4.0, "silent": false, "pitch": 0.78,
		"sound": {"body": 1.3}, "role": "Clip-fed icon. Powerful crack, famous ping.",
		"model": {"style": "classic", "barrel": 0.56, "mag": "internal", "stock": "fixed",
			"sight": "scope", "muzzle": "none", "body": "gunmetal", "accent": "wood", "extras": [], "toprail": false}},
]
